-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity overlay_core is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    stream_in_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    stream_in_TVALID : IN STD_LOGIC;
    stream_in_TREADY : OUT STD_LOGIC;
    stream_in_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_in_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_in_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_out_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    stream_out_TVALID : OUT STD_LOGIC;
    stream_out_TREADY : IN STD_LOGIC;
    stream_out_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    stream_out_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    stream_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_out_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_out_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of overlay_core is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "overlay_core_overlay_core,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=6.667000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.547000,HLS_SYN_LAT=1073676298,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1241,HLS_SYN_LUT=2017,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv17_14 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000010100";
    constant ap_const_lv17_C8 : STD_LOGIC_VECTOR (16 downto 0) := "00000000011001000";
    constant ap_const_lv17_3 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000011";
    constant ap_const_lv17_A : STD_LOGIC_VECTOR (16 downto 0) := "00000000000001010";
    constant ap_const_lv16_5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000101";
    constant ap_const_lv17_B : STD_LOGIC_VECTOR (16 downto 0) := "00000000000001011";
    constant ap_const_lv17_12 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000010010";
    constant ap_const_lv16_B : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001011";
    constant ap_const_lv16_11 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010001";
    constant ap_const_lv16_FFFD : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111101";
    constant ap_const_lv16_FFF5 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111110101";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal enable : STD_LOGIC_VECTOR (0 downto 0);
    signal x_pos : STD_LOGIC_VECTOR (15 downto 0);
    signal y_pos : STD_LOGIC_VECTOR (15 downto 0);
    signal height : STD_LOGIC_VECTOR (15 downto 0);
    signal width : STD_LOGIC_VECTOR (15 downto 0);
    signal width_read_reg_297 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_pos_read_reg_302 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_pos_read_reg_310 : STD_LOGIC_VECTOR (15 downto 0);
    signal enable_read_reg_319 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_i_i564_fu_233_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_i_i564_reg_334 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_i_i533_fu_242_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_i_i533_reg_339 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_i_i486_fu_248_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_i_i486_reg_344 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_i_i458_fu_254_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_i_i458_reg_349 : STD_LOGIC_VECTOR (16 downto 0);
    signal start_x_fu_260_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal start_x_reg_354 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_i_i163_fu_265_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_i_i163_reg_359 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_i_i135_fu_271_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_i_i135_reg_364 : STD_LOGIC_VECTOR (16 downto 0);
    signal char_x_fu_277_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal char_x_reg_369 : STD_LOGIC_VECTOR (15 downto 0);
    signal char_x_2_fu_282_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal char_x_2_reg_374 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_fu_287_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_reg_379 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_1_fu_292_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_1_reg_384 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_224_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln74_reg_389 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_start : STD_LOGIC;
    signal grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_done : STD_LOGIC;
    signal grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_idle : STD_LOGIC;
    signal grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_ready : STD_LOGIC;
    signal grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TREADY : STD_LOGIC;
    signal grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_in_TREADY : STD_LOGIC;
    signal grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TVALID : STD_LOGIC;
    signal grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_fu_224_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_224_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_pos_cast_fu_230_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal x_pos_cast_fu_239_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal regslice_both_stream_out_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal regslice_both_stream_in_V_data_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal stream_in_TVALID_int_regslice : STD_LOGIC;
    signal stream_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_stream_in_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_TKEEP_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_stream_in_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_TSTRB_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_stream_in_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_V_user_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_stream_in_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_V_last_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_stream_in_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_V_id_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_stream_in_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_stream_in_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_V_dest_V_U_ack_in : STD_LOGIC;
    signal stream_out_TVALID_int_regslice : STD_LOGIC;
    signal stream_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_stream_out_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_V_dest_V_U_vld_out : STD_LOGIC;
    signal grp_fu_224_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_224_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_in_TVALID : IN STD_LOGIC;
        stream_out_TREADY : IN STD_LOGIC;
        mul_ln74 : IN STD_LOGIC_VECTOR (31 downto 0);
        width : IN STD_LOGIC_VECTOR (15 downto 0);
        add_i_i486 : IN STD_LOGIC_VECTOR (16 downto 0);
        add_i_i458 : IN STD_LOGIC_VECTOR (16 downto 0);
        y : IN STD_LOGIC_VECTOR (15 downto 0);
        add_i_i163 : IN STD_LOGIC_VECTOR (16 downto 0);
        add_i_i135 : IN STD_LOGIC_VECTOR (16 downto 0);
        y_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        y_pos : IN STD_LOGIC_VECTOR (15 downto 0);
        add_i_i564 : IN STD_LOGIC_VECTOR (16 downto 0);
        stream_in_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        stream_in_TREADY : OUT STD_LOGIC;
        stream_in_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        stream_in_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        stream_in_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_in_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_in_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        x_pos : IN STD_LOGIC_VECTOR (15 downto 0);
        add_i_i533 : IN STD_LOGIC_VECTOR (16 downto 0);
        start_x : IN STD_LOGIC_VECTOR (15 downto 0);
        char_x : IN STD_LOGIC_VECTOR (15 downto 0);
        char_x_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        enable : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_out_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        stream_out_TVALID : OUT STD_LOGIC;
        stream_out_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        stream_out_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        stream_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        stream_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        stream_out_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        stream_out_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component overlay_core_mul_16ns_16ns_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component overlay_core_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        enable : OUT STD_LOGIC_VECTOR (0 downto 0);
        x_pos : OUT STD_LOGIC_VECTOR (15 downto 0);
        y_pos : OUT STD_LOGIC_VECTOR (15 downto 0);
        height : OUT STD_LOGIC_VECTOR (15 downto 0);
        width : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component overlay_core_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154 : component overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_start,
        ap_done => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_done,
        ap_idle => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_idle,
        ap_ready => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_ready,
        stream_in_TVALID => stream_in_TVALID_int_regslice,
        stream_out_TREADY => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TREADY,
        mul_ln74 => mul_ln74_reg_389,
        width => width_read_reg_297,
        add_i_i486 => add_i_i486_reg_344,
        add_i_i458 => add_i_i458_reg_349,
        y => y_reg_379,
        add_i_i163 => add_i_i163_reg_359,
        add_i_i135 => add_i_i135_reg_364,
        y_1 => y_1_reg_384,
        y_pos => y_pos_read_reg_302,
        add_i_i564 => add_i_i564_reg_334,
        stream_in_TDATA => stream_in_TDATA_int_regslice,
        stream_in_TREADY => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_in_TREADY,
        stream_in_TKEEP => stream_in_TKEEP_int_regslice,
        stream_in_TSTRB => stream_in_TSTRB_int_regslice,
        stream_in_TUSER => stream_in_TUSER_int_regslice,
        stream_in_TLAST => stream_in_TLAST_int_regslice,
        stream_in_TID => stream_in_TID_int_regslice,
        stream_in_TDEST => stream_in_TDEST_int_regslice,
        x_pos => x_pos_read_reg_310,
        add_i_i533 => add_i_i533_reg_339,
        start_x => start_x_reg_354,
        char_x => char_x_reg_369,
        char_x_2 => char_x_2_reg_374,
        enable => enable_read_reg_319,
        stream_out_TDATA => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TDATA,
        stream_out_TVALID => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TVALID,
        stream_out_TKEEP => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TKEEP,
        stream_out_TSTRB => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TSTRB,
        stream_out_TUSER => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TUSER,
        stream_out_TLAST => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TLAST,
        stream_out_TID => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TID,
        stream_out_TDEST => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TDEST);

    CTRL_s_axi_U : component overlay_core_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        enable => enable,
        x_pos => x_pos,
        y_pos => y_pos,
        height => height,
        width => width,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    mul_16ns_16ns_32_2_1_U38 : component overlay_core_mul_16ns_16ns_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_224_p0,
        din1 => grp_fu_224_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_224_p2);

    regslice_both_stream_in_V_data_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_TDATA,
        vld_in => stream_in_TVALID,
        ack_in => regslice_both_stream_in_V_data_V_U_ack_in,
        data_out => stream_in_TDATA_int_regslice,
        vld_out => stream_in_TVALID_int_regslice,
        ack_out => stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_V_data_V_U_apdone_blk);

    regslice_both_stream_in_V_keep_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_TKEEP,
        vld_in => stream_in_TVALID,
        ack_in => regslice_both_stream_in_V_keep_V_U_ack_in,
        data_out => stream_in_TKEEP_int_regslice,
        vld_out => regslice_both_stream_in_V_keep_V_U_vld_out,
        ack_out => stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_V_keep_V_U_apdone_blk);

    regslice_both_stream_in_V_strb_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_TSTRB,
        vld_in => stream_in_TVALID,
        ack_in => regslice_both_stream_in_V_strb_V_U_ack_in,
        data_out => stream_in_TSTRB_int_regslice,
        vld_out => regslice_both_stream_in_V_strb_V_U_vld_out,
        ack_out => stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_V_strb_V_U_apdone_blk);

    regslice_both_stream_in_V_user_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_TUSER,
        vld_in => stream_in_TVALID,
        ack_in => regslice_both_stream_in_V_user_V_U_ack_in,
        data_out => stream_in_TUSER_int_regslice,
        vld_out => regslice_both_stream_in_V_user_V_U_vld_out,
        ack_out => stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_V_user_V_U_apdone_blk);

    regslice_both_stream_in_V_last_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_TLAST,
        vld_in => stream_in_TVALID,
        ack_in => regslice_both_stream_in_V_last_V_U_ack_in,
        data_out => stream_in_TLAST_int_regslice,
        vld_out => regslice_both_stream_in_V_last_V_U_vld_out,
        ack_out => stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_V_last_V_U_apdone_blk);

    regslice_both_stream_in_V_id_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_TID,
        vld_in => stream_in_TVALID,
        ack_in => regslice_both_stream_in_V_id_V_U_ack_in,
        data_out => stream_in_TID_int_regslice,
        vld_out => regslice_both_stream_in_V_id_V_U_vld_out,
        ack_out => stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_V_id_V_U_apdone_blk);

    regslice_both_stream_in_V_dest_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_TDEST,
        vld_in => stream_in_TVALID,
        ack_in => regslice_both_stream_in_V_dest_V_U_ack_in,
        data_out => stream_in_TDEST_int_regslice,
        vld_out => regslice_both_stream_in_V_dest_V_U_vld_out,
        ack_out => stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_V_dest_V_U_apdone_blk);

    regslice_both_stream_out_V_data_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TDATA,
        vld_in => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TVALID,
        ack_in => stream_out_TREADY_int_regslice,
        data_out => stream_out_TDATA,
        vld_out => regslice_both_stream_out_V_data_V_U_vld_out,
        ack_out => stream_out_TREADY,
        apdone_blk => regslice_both_stream_out_V_data_V_U_apdone_blk);

    regslice_both_stream_out_V_keep_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TKEEP,
        vld_in => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TVALID,
        ack_in => regslice_both_stream_out_V_keep_V_U_ack_in_dummy,
        data_out => stream_out_TKEEP,
        vld_out => regslice_both_stream_out_V_keep_V_U_vld_out,
        ack_out => stream_out_TREADY,
        apdone_blk => regslice_both_stream_out_V_keep_V_U_apdone_blk);

    regslice_both_stream_out_V_strb_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TSTRB,
        vld_in => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TVALID,
        ack_in => regslice_both_stream_out_V_strb_V_U_ack_in_dummy,
        data_out => stream_out_TSTRB,
        vld_out => regslice_both_stream_out_V_strb_V_U_vld_out,
        ack_out => stream_out_TREADY,
        apdone_blk => regslice_both_stream_out_V_strb_V_U_apdone_blk);

    regslice_both_stream_out_V_user_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TUSER,
        vld_in => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TVALID,
        ack_in => regslice_both_stream_out_V_user_V_U_ack_in_dummy,
        data_out => stream_out_TUSER,
        vld_out => regslice_both_stream_out_V_user_V_U_vld_out,
        ack_out => stream_out_TREADY,
        apdone_blk => regslice_both_stream_out_V_user_V_U_apdone_blk);

    regslice_both_stream_out_V_last_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TLAST,
        vld_in => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TVALID,
        ack_in => regslice_both_stream_out_V_last_V_U_ack_in_dummy,
        data_out => stream_out_TLAST,
        vld_out => regslice_both_stream_out_V_last_V_U_vld_out,
        ack_out => stream_out_TREADY,
        apdone_blk => regslice_both_stream_out_V_last_V_U_apdone_blk);

    regslice_both_stream_out_V_id_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TID,
        vld_in => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TVALID,
        ack_in => regslice_both_stream_out_V_id_V_U_ack_in_dummy,
        data_out => stream_out_TID,
        vld_out => regslice_both_stream_out_V_id_V_U_vld_out,
        ack_out => stream_out_TREADY,
        apdone_blk => regslice_both_stream_out_V_id_V_U_apdone_blk);

    regslice_both_stream_out_V_dest_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TDEST,
        vld_in => grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TVALID,
        ack_in => regslice_both_stream_out_V_dest_V_U_ack_in_dummy,
        data_out => stream_out_TDEST,
        vld_out => regslice_both_stream_out_V_dest_V_U_vld_out,
        ack_out => stream_out_TREADY,
        apdone_blk => regslice_both_stream_out_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_ready = ap_const_logic_1)) then 
                    grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_i_i135_reg_364 <= add_i_i135_fu_271_p2;
                add_i_i163_reg_359 <= add_i_i163_fu_265_p2;
                add_i_i458_reg_349 <= add_i_i458_fu_254_p2;
                add_i_i486_reg_344 <= add_i_i486_fu_248_p2;
                add_i_i533_reg_339 <= add_i_i533_fu_242_p2;
                add_i_i564_reg_334 <= add_i_i564_fu_233_p2;
                char_x_2_reg_374 <= char_x_2_fu_282_p2;
                char_x_reg_369 <= char_x_fu_277_p2;
                mul_ln74_reg_389 <= grp_fu_224_p2;
                start_x_reg_354 <= start_x_fu_260_p2;
                y_1_reg_384 <= y_1_fu_292_p2;
                y_reg_379 <= y_fu_287_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                enable_read_reg_319 <= enable;
                width_read_reg_297 <= width;
                x_pos_read_reg_310 <= x_pos;
                y_pos_read_reg_302 <= y_pos;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_done, ap_CS_fsm_state4, ap_CS_fsm_state5, regslice_both_stream_out_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((regslice_both_stream_out_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_i_i135_fu_271_p2 <= std_logic_vector(unsigned(y_pos_cast_fu_230_p1) + unsigned(ap_const_lv17_12));
    add_i_i163_fu_265_p2 <= std_logic_vector(unsigned(y_pos_cast_fu_230_p1) + unsigned(ap_const_lv17_B));
    add_i_i458_fu_254_p2 <= std_logic_vector(unsigned(y_pos_cast_fu_230_p1) + unsigned(ap_const_lv17_A));
    add_i_i486_fu_248_p2 <= std_logic_vector(unsigned(y_pos_cast_fu_230_p1) + unsigned(ap_const_lv17_3));
    add_i_i533_fu_242_p2 <= std_logic_vector(unsigned(x_pos_cast_fu_239_p1) + unsigned(ap_const_lv17_C8));
    add_i_i564_fu_233_p2 <= std_logic_vector(unsigned(y_pos_cast_fu_230_p1) + unsigned(ap_const_lv17_14));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_done)
    begin
        if ((grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(regslice_both_stream_out_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_stream_out_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state5, regslice_both_stream_out_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_stream_out_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, regslice_both_stream_out_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_stream_out_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    char_x_2_fu_282_p2 <= std_logic_vector(unsigned(x_pos_read_reg_310) + unsigned(ap_const_lv16_11));
    char_x_fu_277_p2 <= std_logic_vector(unsigned(x_pos_read_reg_310) + unsigned(ap_const_lv16_B));
    grp_fu_224_p0 <= grp_fu_224_p00(16 - 1 downto 0);
    grp_fu_224_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height),32));
    grp_fu_224_p1 <= grp_fu_224_p10(16 - 1 downto 0);
    grp_fu_224_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width),32));
    grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_start <= grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_ap_start_reg;
    grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TREADY <= (stream_out_TREADY_int_regslice and ap_CS_fsm_state4);
    start_x_fu_260_p2 <= std_logic_vector(unsigned(x_pos_read_reg_310) + unsigned(ap_const_lv16_5));
    stream_in_TREADY <= regslice_both_stream_in_V_data_V_U_ack_in;

    stream_in_TREADY_int_regslice_assign_proc : process(grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_in_TREADY, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            stream_in_TREADY_int_regslice <= grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_in_TREADY;
        else 
            stream_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    stream_out_TVALID <= regslice_both_stream_out_V_data_V_U_vld_out;
    stream_out_TVALID_int_regslice <= grp_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_fu_154_stream_out_TVALID;
    x_pos_cast_fu_239_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_pos_read_reg_310),17));
    y_1_fu_292_p2 <= std_logic_vector(signed(ap_const_lv16_FFF5) - signed(y_pos_read_reg_302));
    y_fu_287_p2 <= std_logic_vector(signed(ap_const_lv16_FFFD) - signed(y_pos_read_reg_302));
    y_pos_cast_fu_230_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_pos_read_reg_302),17));
end behav;
