-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stream_in_TVALID : IN STD_LOGIC;
    stream_out_TREADY : IN STD_LOGIC;
    mul_ln74 : IN STD_LOGIC_VECTOR (31 downto 0);
    width : IN STD_LOGIC_VECTOR (15 downto 0);
    add_i_i486 : IN STD_LOGIC_VECTOR (16 downto 0);
    add_i_i458 : IN STD_LOGIC_VECTOR (16 downto 0);
    y : IN STD_LOGIC_VECTOR (15 downto 0);
    add_i_i163 : IN STD_LOGIC_VECTOR (16 downto 0);
    add_i_i135 : IN STD_LOGIC_VECTOR (16 downto 0);
    y_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    y_pos : IN STD_LOGIC_VECTOR (15 downto 0);
    add_i_i564 : IN STD_LOGIC_VECTOR (16 downto 0);
    stream_in_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    stream_in_TREADY : OUT STD_LOGIC;
    stream_in_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_in_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_in_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    x_pos : IN STD_LOGIC_VECTOR (15 downto 0);
    add_i_i533 : IN STD_LOGIC_VECTOR (16 downto 0);
    start_x : IN STD_LOGIC_VECTOR (15 downto 0);
    char_x : IN STD_LOGIC_VECTOR (15 downto 0);
    char_x_2 : IN STD_LOGIC_VECTOR (15 downto 0);
    enable : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_out_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    stream_out_TVALID : OUT STD_LOGIC;
    stream_out_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    stream_out_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    stream_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_out_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_out_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";
    constant ap_const_lv16_FFE9 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111101001";
    constant ap_const_lv16_FFE3 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111100011";
    constant ap_const_lv16_6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000110";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln105_fu_437_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal p_ZL8font_5x7_3_3_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_ZL8font_5x7_3_3_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_ZL8font_5x7_2_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_ZL8font_5x7_2_1_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_ZL8font_5x7_2_1_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_ZL8font_5x7_2_1_q1 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_ZL8font_5x7_2_0_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_ZL8font_5x7_2_0_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_ZL8font_5x7_4_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_ZL8font_5x7_4_1_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_ZL8font_5x7_5_2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_ZL8font_5x7_5_2_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_ZL8font_5x7_0_0_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_ZL8font_5x7_0_0_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_ZL8font_5x7_1_3_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_ZL8font_5x7_1_3_q0 : STD_LOGIC_VECTOR (1 downto 0);
    signal stream_in_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal stream_out_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal pixel_in_data_reg_1259 : STD_LOGIC_VECTOR (23 downto 0);
    signal pixel_in_data_reg_1259_pp0_iter1_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal pixel_in_data_reg_1259_pp0_iter2_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal pixel_in_data_reg_1259_pp0_iter3_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal pixel_in_keep_reg_1266 : STD_LOGIC_VECTOR (2 downto 0);
    signal pixel_in_keep_reg_1266_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal pixel_in_keep_reg_1266_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal pixel_in_keep_reg_1266_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal pixel_in_user_reg_1271 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_user_reg_1271_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_user_reg_1271_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_user_reg_1271_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_last_reg_1276 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_last_reg_1276_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_last_reg_1276_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_last_reg_1276_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal r_reg_1281 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_reg_1281_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal r_reg_1281_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal r_reg_1281_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal g_reg_1287 : STD_LOGIC_VECTOR (7 downto 0);
    signal g_reg_1287_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal g_reg_1287_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal g_reg_1287_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal b_fu_485_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_reg_1293 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_reg_1293_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal b_reg_1293_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal b_reg_1293_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln105_fu_505_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln105_reg_1299 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln105_1_fu_519_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln105_1_reg_1310 : STD_LOGIC_VECTOR (15 downto 0);
    signal ult_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ult_reg_1318 : STD_LOGIC_VECTOR (0 downto 0);
    signal ult_reg_1318_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i435_fu_551_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i435_reg_1323 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i435_reg_1323_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal rel_y_fu_556_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal rel_y_reg_1328 : STD_LOGIC_VECTOR (15 downto 0);
    signal ult39_fu_560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ult39_reg_1334 : STD_LOGIC_VECTOR (0 downto 0);
    signal ult39_reg_1334_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i112_fu_565_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i112_reg_1339 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i112_reg_1339_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal rel_y_1_fu_570_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal rel_y_1_reg_1344 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln122_1_fu_619_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln122_1_reg_1350 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln122_1_reg_1350_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_fu_629_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_reg_1357 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_reg_1357_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_1_fu_645_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_1_reg_1368 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_1_reg_1368_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_2_fu_661_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_2_reg_1379 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_2_reg_1379_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal rel_x_3_fu_678_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal rel_x_3_reg_1390 : STD_LOGIC_VECTOR (15 downto 0);
    signal rel_x_4_fu_693_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal rel_x_4_reg_1400 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_fu_712_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_reg_1425 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_18_fu_725_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_18_reg_1430 : STD_LOGIC_VECTOR (6 downto 0);
    signal cmp_i_i17_i_i319_not_fu_729_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i_i17_i_i319_not_reg_1435 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i_i17_i_i_not_fu_734_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i_i17_i_i_not_reg_1444 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_2_reg_1451 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln49_3_fu_751_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_3_reg_1456 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_4_fu_762_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_4_reg_1461 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_fu_773_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_reg_1466 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_1_fu_779_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_1_reg_1471 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_3_fu_785_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_3_reg_1476 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_4_fu_791_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_4_reg_1481 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_5_reg_1486 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln52_6_fu_817_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_6_reg_1491 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_7_fu_823_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_7_reg_1496 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln51_fu_635_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln51_1_fu_651_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln51_2_fu_667_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln51_3_fu_683_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln51_4_fu_698_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal pixel_x_fu_162 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal add_ln106_fu_527_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal row_fu_166 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal indvar_flatten_fu_170 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_ln105_fu_443_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal p_ZL8font_5x7_3_3_ce0_local : STD_LOGIC;
    signal p_ZL8font_5x7_2_1_ce1_local : STD_LOGIC;
    signal p_ZL8font_5x7_2_1_ce0_local : STD_LOGIC;
    signal p_ZL8font_5x7_2_0_ce0_local : STD_LOGIC;
    signal p_ZL8font_5x7_4_1_ce0_local : STD_LOGIC;
    signal p_ZL8font_5x7_5_2_ce0_local : STD_LOGIC;
    signal p_ZL8font_5x7_0_0_ce0_local : STD_LOGIC;
    signal p_ZL8font_5x7_1_3_ce0_local : STD_LOGIC;
    signal icmp_ln106_fu_500_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln105_1_fu_513_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal row_cast_fu_543_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ult41_fu_574_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln123_fu_589_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln123_fu_599_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal rev42_fu_578_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln123_fu_593_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal notrhs_fu_584_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln123_1_fu_602_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln122_2_fu_613_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln122_fu_607_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rel_x_fu_625_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal rel_x_1_fu_641_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal rel_x_2_fu_657_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal char_x_4_fu_673_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal char_x_5_fu_688_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sh_prom_i_i327_fu_703_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_i_i328_fu_706_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sh_prom_i_i_fu_716_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_i_i_fu_719_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln52_fu_739_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal and_ln52_1_fu_745_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal and_ln52_3_fu_756_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal and_ln52_4_fu_767_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln51_fu_797_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln51_1_fu_807_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal and_ln52_6_fu_801_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal and_ln52_7_fu_811_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal rev40_fu_834_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_1_fu_844_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal g_1_fu_857_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal b_1_fu_870_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln126_fu_866_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln125_fu_853_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln127_fu_879_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln49_fu_901_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln49_fu_925_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln49_1_fu_905_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln49_1_fu_936_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln49_2_fu_909_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_2_fu_913_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln52_2_fu_953_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln49_2_fu_947_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln49_3_fu_917_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln49_3_fu_965_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln49_4_fu_921_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln49_4_fu_976_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_8_fu_931_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_9_fu_942_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_11_fu_971_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_12_fu_982_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln52_1_fu_993_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_10_fu_959_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln52_2_fu_999_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln52_fu_987_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln52_3_fu_1005_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_13_fu_1011_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_829_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln49_5_fu_1022_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_5_fu_1026_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln52_5_fu_1044_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln49_5_fu_1038_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln49_6_fu_1030_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln49_6_fu_1056_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln49_7_fu_1034_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln49_7_fu_1067_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_16_fu_1062_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_17_fu_1073_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln52_4_fu_1078_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_15_fu_1050_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal spec_select1222_fu_839_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_20_fu_1084_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal draw_pixel_fu_1016_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal draw_pixel_1_fu_1090_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal draw_pixel_2_fu_1096_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln122_1_fu_889_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln122_fu_883_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_3_fu_895_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_3_fu_1102_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal g_3_fu_1110_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_4_fu_1118_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_2_fu_1126_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal g_2_fu_1132_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_2_fu_1138_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_3_3_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_2_1_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_2_0_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_4_1_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_5_2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_0_0_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_1_3_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component overlay_core_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    p_ZL8font_5x7_3_3_U : component overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_3_3_ROM_AUTO_1R
    generic map (
        DataWidth => 7,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL8font_5x7_3_3_address0,
        ce0 => p_ZL8font_5x7_3_3_ce0_local,
        q0 => p_ZL8font_5x7_3_3_q0);

    p_ZL8font_5x7_2_1_U : component overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_2_1_ROM_AUTO_1R
    generic map (
        DataWidth => 7,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL8font_5x7_2_1_address0,
        ce0 => p_ZL8font_5x7_2_1_ce0_local,
        q0 => p_ZL8font_5x7_2_1_q0,
        address1 => p_ZL8font_5x7_2_1_address1,
        ce1 => p_ZL8font_5x7_2_1_ce1_local,
        q1 => p_ZL8font_5x7_2_1_q1);

    p_ZL8font_5x7_2_0_U : component overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_2_0_ROM_AUTO_1R
    generic map (
        DataWidth => 7,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL8font_5x7_2_0_address0,
        ce0 => p_ZL8font_5x7_2_0_ce0_local,
        q0 => p_ZL8font_5x7_2_0_q0);

    p_ZL8font_5x7_4_1_U : component overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_4_1_ROM_AUTO_1R
    generic map (
        DataWidth => 7,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL8font_5x7_4_1_address0,
        ce0 => p_ZL8font_5x7_4_1_ce0_local,
        q0 => p_ZL8font_5x7_4_1_q0);

    p_ZL8font_5x7_5_2_U : component overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_5_2_ROM_AUTO_1R
    generic map (
        DataWidth => 7,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL8font_5x7_5_2_address0,
        ce0 => p_ZL8font_5x7_5_2_ce0_local,
        q0 => p_ZL8font_5x7_5_2_q0);

    p_ZL8font_5x7_0_0_U : component overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_0_0_ROM_AUTO_1R
    generic map (
        DataWidth => 6,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL8font_5x7_0_0_address0,
        ce0 => p_ZL8font_5x7_0_0_ce0_local,
        q0 => p_ZL8font_5x7_0_0_q0);

    p_ZL8font_5x7_1_3_U : component overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_1_3_ROM_AUTO_1R
    generic map (
        DataWidth => 2,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL8font_5x7_1_3_address0,
        ce0 => p_ZL8font_5x7_1_3_ce0_local,
        q0 => p_ZL8font_5x7_1_3_q0);

    flow_control_loop_pipe_sequential_init_U : component overlay_core_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln105_fu_437_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1))) then 
                    indvar_flatten_fu_170 <= add_ln105_fu_443_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_170 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    pixel_x_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    pixel_x_fu_162 <= ap_const_lv16_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    pixel_x_fu_162 <= add_ln106_fu_527_p2;
                end if;
            end if; 
        end if;
    end process;

    row_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    row_fu_166 <= ap_const_lv16_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    row_fu_166 <= select_ln105_1_fu_519_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                and_ln122_1_reg_1350 <= and_ln122_1_fu_619_p2;
                and_ln122_1_reg_1350_pp0_iter3_reg <= and_ln122_1_reg_1350;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                b_reg_1293_pp0_iter2_reg <= b_reg_1293_pp0_iter1_reg;
                b_reg_1293_pp0_iter3_reg <= b_reg_1293_pp0_iter2_reg;
                cmp_i112_reg_1339 <= cmp_i112_fu_565_p2;
                cmp_i112_reg_1339_pp0_iter3_reg <= cmp_i112_reg_1339;
                cmp_i435_reg_1323 <= cmp_i435_fu_551_p2;
                cmp_i435_reg_1323_pp0_iter3_reg <= cmp_i435_reg_1323;
                cmp_i_i17_i_i319_not_reg_1435 <= cmp_i_i17_i_i319_not_fu_729_p2;
                cmp_i_i17_i_i_not_reg_1444 <= cmp_i_i17_i_i_not_fu_734_p2;
                col_2_reg_1451 <= p_ZL8font_5x7_2_0_q0;
                col_5_reg_1486 <= p_ZL8font_5x7_5_2_q0;
                empty_18_reg_1430 <= empty_18_fu_725_p1;
                empty_reg_1425 <= empty_fu_712_p1;
                g_reg_1287_pp0_iter2_reg <= g_reg_1287_pp0_iter1_reg;
                g_reg_1287_pp0_iter3_reg <= g_reg_1287_pp0_iter2_reg;
                icmp_ln49_1_reg_1368 <= icmp_ln49_1_fu_645_p2;
                icmp_ln49_1_reg_1368_pp0_iter3_reg <= icmp_ln49_1_reg_1368;
                icmp_ln49_2_reg_1379 <= icmp_ln49_2_fu_661_p2;
                icmp_ln49_2_reg_1379_pp0_iter3_reg <= icmp_ln49_2_reg_1379;
                icmp_ln49_3_reg_1456 <= icmp_ln49_3_fu_751_p2;
                icmp_ln49_4_reg_1461 <= icmp_ln49_4_fu_762_p2;
                icmp_ln49_reg_1357 <= icmp_ln49_fu_629_p2;
                icmp_ln49_reg_1357_pp0_iter3_reg <= icmp_ln49_reg_1357;
                icmp_ln52_1_reg_1471 <= icmp_ln52_1_fu_779_p2;
                icmp_ln52_3_reg_1476 <= icmp_ln52_3_fu_785_p2;
                icmp_ln52_4_reg_1481 <= icmp_ln52_4_fu_791_p2;
                icmp_ln52_6_reg_1491 <= icmp_ln52_6_fu_817_p2;
                icmp_ln52_7_reg_1496 <= icmp_ln52_7_fu_823_p2;
                icmp_ln52_reg_1466 <= icmp_ln52_fu_773_p2;
                pixel_in_data_reg_1259_pp0_iter2_reg <= pixel_in_data_reg_1259_pp0_iter1_reg;
                pixel_in_data_reg_1259_pp0_iter3_reg <= pixel_in_data_reg_1259_pp0_iter2_reg;
                pixel_in_keep_reg_1266_pp0_iter2_reg <= pixel_in_keep_reg_1266_pp0_iter1_reg;
                pixel_in_keep_reg_1266_pp0_iter3_reg <= pixel_in_keep_reg_1266_pp0_iter2_reg;
                pixel_in_last_reg_1276_pp0_iter2_reg <= pixel_in_last_reg_1276_pp0_iter1_reg;
                pixel_in_last_reg_1276_pp0_iter3_reg <= pixel_in_last_reg_1276_pp0_iter2_reg;
                pixel_in_user_reg_1271_pp0_iter2_reg <= pixel_in_user_reg_1271_pp0_iter1_reg;
                pixel_in_user_reg_1271_pp0_iter3_reg <= pixel_in_user_reg_1271_pp0_iter2_reg;
                r_reg_1281_pp0_iter2_reg <= r_reg_1281_pp0_iter1_reg;
                r_reg_1281_pp0_iter3_reg <= r_reg_1281_pp0_iter2_reg;
                rel_x_3_reg_1390 <= rel_x_3_fu_678_p2;
                rel_x_4_reg_1400 <= rel_x_4_fu_693_p2;
                rel_y_1_reg_1344 <= rel_y_1_fu_570_p2;
                rel_y_reg_1328 <= rel_y_fu_556_p2;
                ult39_reg_1334 <= ult39_fu_560_p2;
                ult39_reg_1334_pp0_iter3_reg <= ult39_reg_1334;
                ult_reg_1318 <= ult_fu_546_p2;
                ult_reg_1318_pp0_iter3_reg <= ult_reg_1318;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                b_reg_1293 <= b_fu_485_p1;
                b_reg_1293_pp0_iter1_reg <= b_reg_1293;
                g_reg_1287 <= stream_in_TDATA(15 downto 8);
                g_reg_1287_pp0_iter1_reg <= g_reg_1287;
                pixel_in_data_reg_1259 <= stream_in_TDATA;
                pixel_in_data_reg_1259_pp0_iter1_reg <= pixel_in_data_reg_1259;
                pixel_in_keep_reg_1266 <= stream_in_TKEEP;
                pixel_in_keep_reg_1266_pp0_iter1_reg <= pixel_in_keep_reg_1266;
                pixel_in_last_reg_1276 <= stream_in_TLAST;
                pixel_in_last_reg_1276_pp0_iter1_reg <= pixel_in_last_reg_1276;
                pixel_in_user_reg_1271 <= stream_in_TUSER;
                pixel_in_user_reg_1271_pp0_iter1_reg <= pixel_in_user_reg_1271;
                r_reg_1281 <= stream_in_TDATA(23 downto 16);
                r_reg_1281_pp0_iter1_reg <= r_reg_1281;
                select_ln105_1_reg_1310 <= select_ln105_1_fu_519_p3;
                select_ln105_reg_1299 <= select_ln105_fu_505_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln105_1_fu_513_p2 <= std_logic_vector(unsigned(row_fu_166) + unsigned(ap_const_lv16_1));
    add_ln105_fu_443_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv32_1));
    add_ln106_fu_527_p2 <= std_logic_vector(unsigned(select_ln105_fu_505_p3) + unsigned(ap_const_lv16_1));
    and_ln122_1_fu_619_p2 <= (and_ln122_fu_607_p2 and and_ln122_2_fu_613_p2);
    and_ln122_2_fu_613_p2 <= (notrhs_fu_584_p2 and icmp_ln123_1_fu_602_p2);
    and_ln122_fu_607_p2 <= (xor_ln123_fu_593_p2 and rev42_fu_578_p2);
    and_ln52_10_fu_959_p2 <= (xor_ln49_2_fu_947_p2 and icmp_ln52_2_fu_953_p2);
    and_ln52_11_fu_971_p2 <= (xor_ln49_3_fu_965_p2 and icmp_ln52_3_reg_1476);
    and_ln52_12_fu_982_p2 <= (xor_ln49_4_fu_976_p2 and icmp_ln52_4_reg_1481);
    and_ln52_13_fu_1011_p2 <= (or_ln52_3_fu_1005_p2 and cmp_i435_reg_1323_pp0_iter3_reg);
    and_ln52_15_fu_1050_p2 <= (xor_ln49_5_fu_1038_p2 and icmp_ln52_5_fu_1044_p2);
    and_ln52_16_fu_1062_p2 <= (xor_ln49_6_fu_1056_p2 and icmp_ln52_6_reg_1491);
    and_ln52_17_fu_1073_p2 <= (xor_ln49_7_fu_1067_p2 and icmp_ln52_7_reg_1496);
    and_ln52_1_fu_745_p2 <= (p_ZL8font_5x7_2_1_q1 and empty_fu_712_p1);
    and_ln52_2_fu_913_p2 <= (empty_reg_1425 and col_2_reg_1451);
    and_ln52_3_fu_756_p2 <= (p_ZL8font_5x7_4_1_q0 and empty_fu_712_p1);
    and_ln52_4_fu_767_p2 <= (p_ZL8font_5x7_2_1_q0 and empty_fu_712_p1);
    and_ln52_5_fu_1026_p2 <= (empty_18_reg_1430 and col_5_reg_1486);
    and_ln52_6_fu_801_p2 <= (sext_ln51_fu_797_p1 and empty_18_fu_725_p1);
    and_ln52_7_fu_811_p2 <= (sext_ln51_1_fu_807_p1 and empty_18_fu_725_p1);
    and_ln52_8_fu_931_p2 <= (xor_ln49_fu_925_p2 and icmp_ln52_reg_1466);
    and_ln52_9_fu_942_p2 <= (xor_ln49_1_fu_936_p2 and icmp_ln52_1_reg_1471);
    and_ln52_fu_739_p2 <= (p_ZL8font_5x7_3_3_q0 and empty_fu_712_p1);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_state1_pp0_stage0_iter0, ap_block_state5_pp0_stage0_iter4, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_state1_pp0_stage0_iter0, stream_out_TREADY, ap_block_state5_pp0_stage0_iter4, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and ((stream_out_TREADY = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4))) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_state1_pp0_stage0_iter0, stream_out_TREADY, ap_block_state5_pp0_stage0_iter4, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and ((stream_out_TREADY = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4))) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(stream_in_TVALID, icmp_ln105_fu_437_p2)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((icmp_ln105_fu_437_p2 = ap_const_lv1_0) and (stream_in_TVALID = ap_const_logic_0));
    end process;


    ap_block_state5_pp0_stage0_iter4_assign_proc : process(stream_out_TREADY)
    begin
                ap_block_state5_pp0_stage0_iter4 <= (stream_out_TREADY = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln105_fu_437_p2, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln105_fu_437_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_170)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv32_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_170;
        end if; 
    end process;

    b_1_fu_870_p4 <= pixel_in_data_reg_1259_pp0_iter3_reg(7 downto 1);
    b_2_fu_1138_p3 <= 
        b_4_fu_1118_p3 when (enable(0) = '1') else 
        b_reg_1293_pp0_iter3_reg;
    b_3_fu_895_p3 <= 
        zext_ln127_fu_879_p1 when (and_ln122_1_reg_1350_pp0_iter3_reg(0) = '1') else 
        b_reg_1293_pp0_iter3_reg;
    b_4_fu_1118_p3 <= 
        ap_const_lv8_FF when (draw_pixel_2_fu_1096_p2(0) = '1') else 
        b_3_fu_895_p3;
    b_fu_485_p1 <= stream_in_TDATA(8 - 1 downto 0);
    char_x_4_fu_673_p2 <= std_logic_vector(signed(ap_const_lv16_FFE9) - signed(x_pos));
    char_x_5_fu_688_p2 <= std_logic_vector(signed(ap_const_lv16_FFE3) - signed(x_pos));
    cmp_i112_fu_565_p2 <= "1" when (unsigned(add_i_i135) > unsigned(row_cast_fu_543_p1)) else "0";
    cmp_i435_fu_551_p2 <= "1" when (unsigned(add_i_i458) > unsigned(row_cast_fu_543_p1)) else "0";
    cmp_i_i17_i_i319_not_fu_729_p2 <= "1" when (unsigned(rel_y_reg_1328) > unsigned(ap_const_lv16_6)) else "0";
    cmp_i_i17_i_i_not_fu_734_p2 <= "1" when (unsigned(rel_y_1_reg_1344) > unsigned(ap_const_lv16_6)) else "0";
    draw_pixel_1_fu_1090_p2 <= (spec_select1222_fu_839_p2 and empty_20_fu_1084_p2);
    draw_pixel_2_fu_1096_p2 <= (draw_pixel_fu_1016_p2 or draw_pixel_1_fu_1090_p2);
    draw_pixel_fu_1016_p2 <= (rev_fu_829_p2 and and_ln52_13_fu_1011_p2);
    empty_18_fu_725_p1 <= shl_i_i_fu_719_p2(7 - 1 downto 0);
    empty_20_fu_1084_p2 <= (or_ln52_4_fu_1078_p2 or and_ln52_15_fu_1050_p2);
    empty_fu_712_p1 <= shl_i_i328_fu_706_p2(7 - 1 downto 0);
    g_1_fu_857_p4 <= pixel_in_data_reg_1259_pp0_iter3_reg(15 downto 9);
    g_2_fu_1132_p3 <= 
        g_3_fu_1110_p3 when (enable(0) = '1') else 
        g_reg_1287_pp0_iter3_reg;
    g_3_fu_1110_p3 <= 
        ap_const_lv8_FF when (draw_pixel_2_fu_1096_p2(0) = '1') else 
        select_ln122_fu_883_p3;
    icmp_ln105_fu_437_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = mul_ln74) else "0";
    icmp_ln106_fu_500_p2 <= "1" when (pixel_x_fu_162 = width) else "0";
    icmp_ln123_1_fu_602_p2 <= "1" when (unsigned(add_i_i533) > unsigned(zext_ln123_fu_599_p1)) else "0";
    icmp_ln123_fu_589_p2 <= "1" when (unsigned(select_ln105_reg_1299) < unsigned(x_pos)) else "0";
    icmp_ln49_1_fu_645_p2 <= "1" when (unsigned(rel_x_1_fu_641_p2) > unsigned(ap_const_lv16_4)) else "0";
    icmp_ln49_2_fu_661_p2 <= "1" when (unsigned(rel_x_2_fu_657_p2) > unsigned(ap_const_lv16_4)) else "0";
    icmp_ln49_3_fu_751_p2 <= "1" when (unsigned(rel_x_3_reg_1390) > unsigned(ap_const_lv16_4)) else "0";
    icmp_ln49_4_fu_762_p2 <= "1" when (unsigned(rel_x_4_reg_1400) > unsigned(ap_const_lv16_4)) else "0";
    icmp_ln49_fu_629_p2 <= "1" when (unsigned(rel_x_fu_625_p2) > unsigned(ap_const_lv16_4)) else "0";
    icmp_ln52_1_fu_779_p2 <= "0" when (and_ln52_1_fu_745_p2 = ap_const_lv7_0) else "1";
    icmp_ln52_2_fu_953_p2 <= "0" when (and_ln52_2_fu_913_p2 = ap_const_lv7_0) else "1";
    icmp_ln52_3_fu_785_p2 <= "0" when (and_ln52_3_fu_756_p2 = ap_const_lv7_0) else "1";
    icmp_ln52_4_fu_791_p2 <= "0" when (and_ln52_4_fu_767_p2 = ap_const_lv7_0) else "1";
    icmp_ln52_5_fu_1044_p2 <= "0" when (and_ln52_5_fu_1026_p2 = ap_const_lv7_0) else "1";
    icmp_ln52_6_fu_817_p2 <= "0" when (and_ln52_6_fu_801_p2 = ap_const_lv7_0) else "1";
    icmp_ln52_7_fu_823_p2 <= "0" when (and_ln52_7_fu_811_p2 = ap_const_lv7_0) else "1";
    icmp_ln52_fu_773_p2 <= "0" when (and_ln52_fu_739_p2 = ap_const_lv7_0) else "1";
    notrhs_fu_584_p2 <= "1" when (unsigned(add_i_i564) > unsigned(row_cast_fu_543_p1)) else "0";
    or_ln49_1_fu_905_p2 <= (icmp_ln49_1_reg_1368_pp0_iter3_reg or cmp_i_i17_i_i319_not_reg_1435);
    or_ln49_2_fu_909_p2 <= (icmp_ln49_2_reg_1379_pp0_iter3_reg or cmp_i_i17_i_i319_not_reg_1435);
    or_ln49_3_fu_917_p2 <= (icmp_ln49_3_reg_1456 or cmp_i_i17_i_i319_not_reg_1435);
    or_ln49_4_fu_921_p2 <= (icmp_ln49_4_reg_1461 or cmp_i_i17_i_i319_not_reg_1435);
    or_ln49_5_fu_1022_p2 <= (icmp_ln49_reg_1357_pp0_iter3_reg or cmp_i_i17_i_i_not_reg_1444);
    or_ln49_6_fu_1030_p2 <= (icmp_ln49_1_reg_1368_pp0_iter3_reg or cmp_i_i17_i_i_not_reg_1444);
    or_ln49_7_fu_1034_p2 <= (icmp_ln49_2_reg_1379_pp0_iter3_reg or cmp_i_i17_i_i_not_reg_1444);
    or_ln49_fu_901_p2 <= (icmp_ln49_reg_1357_pp0_iter3_reg or cmp_i_i17_i_i319_not_reg_1435);
    or_ln52_1_fu_993_p2 <= (and_ln52_12_fu_982_p2 or and_ln52_11_fu_971_p2);
    or_ln52_2_fu_999_p2 <= (or_ln52_1_fu_993_p2 or and_ln52_10_fu_959_p2);
    or_ln52_3_fu_1005_p2 <= (or_ln52_fu_987_p2 or or_ln52_2_fu_999_p2);
    or_ln52_4_fu_1078_p2 <= (and_ln52_17_fu_1073_p2 or and_ln52_16_fu_1062_p2);
    or_ln52_fu_987_p2 <= (and_ln52_9_fu_942_p2 or and_ln52_8_fu_931_p2);
    p_ZL8font_5x7_0_0_address0 <= zext_ln51_1_fu_651_p1(3 - 1 downto 0);

    p_ZL8font_5x7_0_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL8font_5x7_0_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZL8font_5x7_0_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL8font_5x7_1_3_address0 <= zext_ln51_2_fu_667_p1(3 - 1 downto 0);

    p_ZL8font_5x7_1_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL8font_5x7_1_3_ce0_local <= ap_const_logic_1;
        else 
            p_ZL8font_5x7_1_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL8font_5x7_2_0_address0 <= zext_ln51_2_fu_667_p1(3 - 1 downto 0);

    p_ZL8font_5x7_2_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL8font_5x7_2_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZL8font_5x7_2_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL8font_5x7_2_1_address0 <= zext_ln51_4_fu_698_p1(3 - 1 downto 0);
    p_ZL8font_5x7_2_1_address1 <= zext_ln51_1_fu_651_p1(3 - 1 downto 0);

    p_ZL8font_5x7_2_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL8font_5x7_2_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZL8font_5x7_2_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    p_ZL8font_5x7_2_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL8font_5x7_2_1_ce1_local <= ap_const_logic_1;
        else 
            p_ZL8font_5x7_2_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL8font_5x7_3_3_address0 <= zext_ln51_fu_635_p1(3 - 1 downto 0);

    p_ZL8font_5x7_3_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL8font_5x7_3_3_ce0_local <= ap_const_logic_1;
        else 
            p_ZL8font_5x7_3_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL8font_5x7_4_1_address0 <= zext_ln51_3_fu_683_p1(3 - 1 downto 0);

    p_ZL8font_5x7_4_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL8font_5x7_4_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZL8font_5x7_4_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL8font_5x7_5_2_address0 <= zext_ln51_fu_635_p1(3 - 1 downto 0);

    p_ZL8font_5x7_5_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL8font_5x7_5_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZL8font_5x7_5_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    r_1_fu_844_p4 <= pixel_in_data_reg_1259_pp0_iter3_reg(23 downto 17);
    r_2_fu_1126_p3 <= 
        r_3_fu_1102_p3 when (enable(0) = '1') else 
        r_reg_1281_pp0_iter3_reg;
    r_3_fu_1102_p3 <= 
        ap_const_lv8_FF when (draw_pixel_2_fu_1096_p2(0) = '1') else 
        select_ln122_1_fu_889_p3;
    rel_x_1_fu_641_p2 <= std_logic_vector(unsigned(select_ln105_reg_1299) - unsigned(char_x));
    rel_x_2_fu_657_p2 <= std_logic_vector(unsigned(select_ln105_reg_1299) - unsigned(char_x_2));
    rel_x_3_fu_678_p2 <= std_logic_vector(unsigned(select_ln105_reg_1299) + unsigned(char_x_4_fu_673_p2));
    rel_x_4_fu_693_p2 <= std_logic_vector(unsigned(select_ln105_reg_1299) + unsigned(char_x_5_fu_688_p2));
    rel_x_fu_625_p2 <= std_logic_vector(unsigned(select_ln105_reg_1299) - unsigned(start_x));
    rel_y_1_fu_570_p2 <= std_logic_vector(unsigned(select_ln105_1_reg_1310) + unsigned(y_1));
    rel_y_fu_556_p2 <= std_logic_vector(unsigned(select_ln105_1_reg_1310) + unsigned(y));
    rev40_fu_834_p2 <= (ult39_reg_1334_pp0_iter3_reg xor ap_const_lv1_1);
    rev42_fu_578_p2 <= (ult41_fu_574_p2 xor ap_const_lv1_1);
    rev_fu_829_p2 <= (ult_reg_1318_pp0_iter3_reg xor ap_const_lv1_1);
    row_cast_fu_543_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln105_1_reg_1310),17));
    select_ln105_1_fu_519_p3 <= 
        add_ln105_1_fu_513_p2 when (icmp_ln106_fu_500_p2(0) = '1') else 
        row_fu_166;
    select_ln105_fu_505_p3 <= 
        ap_const_lv16_0 when (icmp_ln106_fu_500_p2(0) = '1') else 
        pixel_x_fu_162;
    select_ln122_1_fu_889_p3 <= 
        zext_ln125_fu_853_p1 when (and_ln122_1_reg_1350_pp0_iter3_reg(0) = '1') else 
        r_reg_1281_pp0_iter3_reg;
    select_ln122_fu_883_p3 <= 
        zext_ln126_fu_866_p1 when (and_ln122_1_reg_1350_pp0_iter3_reg(0) = '1') else 
        g_reg_1287_pp0_iter3_reg;
        sext_ln51_1_fu_807_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_ZL8font_5x7_1_3_q0),7));

        sext_ln51_fu_797_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_ZL8font_5x7_0_0_q0),7));

    sh_prom_i_i327_fu_703_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rel_y_reg_1328),32));
    sh_prom_i_i_fu_716_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rel_y_1_reg_1344),32));
    shl_i_i328_fu_706_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv32_1),to_integer(unsigned('0' & sh_prom_i_i327_fu_703_p1(31-1 downto 0)))));
    shl_i_i_fu_719_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv32_1),to_integer(unsigned('0' & sh_prom_i_i_fu_716_p1(31-1 downto 0)))));
    spec_select1222_fu_839_p2 <= (rev40_fu_834_p2 and cmp_i112_reg_1339_pp0_iter3_reg);

    stream_in_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, stream_in_TVALID, icmp_ln105_fu_437_p2, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln105_fu_437_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_TDATA_blk_n <= stream_in_TVALID;
        else 
            stream_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_in_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln105_fu_437_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln105_fu_437_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_TREADY <= ap_const_logic_1;
        else 
            stream_in_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    stream_out_TDATA <= ((r_2_fu_1126_p3 & g_2_fu_1132_p3) & b_2_fu_1138_p3);

    stream_out_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter4, stream_out_TREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            stream_out_TDATA_blk_n <= stream_out_TREADY;
        else 
            stream_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_out_TDEST <= "X";
    stream_out_TID <= "X";
    stream_out_TKEEP <= pixel_in_keep_reg_1266_pp0_iter3_reg;
    stream_out_TLAST <= pixel_in_last_reg_1276_pp0_iter3_reg;
    stream_out_TSTRB <= "XXX";
    stream_out_TUSER <= pixel_in_user_reg_1271_pp0_iter3_reg;

    stream_out_TVALID_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            stream_out_TVALID <= ap_const_logic_1;
        else 
            stream_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    ult39_fu_560_p2 <= "1" when (unsigned(row_cast_fu_543_p1) < unsigned(add_i_i163)) else "0";
    ult41_fu_574_p2 <= "1" when (unsigned(select_ln105_1_reg_1310) < unsigned(y_pos)) else "0";
    ult_fu_546_p2 <= "1" when (unsigned(row_cast_fu_543_p1) < unsigned(add_i_i486)) else "0";
    xor_ln123_fu_593_p2 <= (icmp_ln123_fu_589_p2 xor ap_const_lv1_1);
    xor_ln49_1_fu_936_p2 <= (or_ln49_1_fu_905_p2 xor ap_const_lv1_1);
    xor_ln49_2_fu_947_p2 <= (or_ln49_2_fu_909_p2 xor ap_const_lv1_1);
    xor_ln49_3_fu_965_p2 <= (or_ln49_3_fu_917_p2 xor ap_const_lv1_1);
    xor_ln49_4_fu_976_p2 <= (or_ln49_4_fu_921_p2 xor ap_const_lv1_1);
    xor_ln49_5_fu_1038_p2 <= (or_ln49_5_fu_1022_p2 xor ap_const_lv1_1);
    xor_ln49_6_fu_1056_p2 <= (or_ln49_6_fu_1030_p2 xor ap_const_lv1_1);
    xor_ln49_7_fu_1067_p2 <= (or_ln49_7_fu_1034_p2 xor ap_const_lv1_1);
    xor_ln49_fu_925_p2 <= (or_ln49_fu_901_p2 xor ap_const_lv1_1);
    zext_ln123_fu_599_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln105_reg_1299),17));
    zext_ln125_fu_853_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_1_fu_844_p4),8));
    zext_ln126_fu_866_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(g_1_fu_857_p4),8));
    zext_ln127_fu_879_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_1_fu_870_p4),8));
    zext_ln51_1_fu_651_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rel_x_1_fu_641_p2),64));
    zext_ln51_2_fu_667_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rel_x_2_fu_657_p2),64));
    zext_ln51_3_fu_683_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rel_x_3_fu_678_p2),64));
    zext_ln51_4_fu_698_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rel_x_4_fu_693_p2),64));
    zext_ln51_fu_635_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rel_x_fu_625_p2),64));
end behav;
