#!/bin/bash -f
#**********************************************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Script generated by Vivado on Sun Apr 26 19:53:32 +0100 2026
# SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : system.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : system.sh
#                system.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                system.sh [-reset_run]
#                system.sh [-reset_log]
#                system.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'system.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname xil_defaultlib -libname fifo_generator_v13_2_10 -libname axis_infrastructure_v1_1_1 -libname axis_data_fifo_v2_0_13 -libname axi_infrastructure_v1_1_0 -libname axi_vip_v1_1_17 -libname processing_system7_vip_v1_0_19 -libname lib_cdc_v1_0_3 -libname proc_sys_reset_v5_0_15 -libname xlconcat_v2_1_6 -libname lib_pkg_v1_0_4 -libname lib_fifo_v1_0_19 -libname blk_mem_gen_v8_4_8 -libname lib_bmg_v1_0_17 -libname lib_srl_fifo_v1_0_4 -libname axi_datamover_v5_1_33 -libname axi_vdma_v6_3_19 -libname generic_baseblocks_v2_1_2 -libname axi_register_slice_v2_1_31 -libname axi_data_fifo_v2_1_30 -libname axi_crossbar_v2_1_32 -libname axi_lite_ipif_v3_0_4 -libname v_tc_v6_1_14 -libname v_vid_in_axi4s_v4_0_11 -libname v_axi4s_vid_out_v4_0_18 -libname v_tc_v6_2_8 -libname axi_protocol_converter_v2_1_31 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm xil_defaultlib fifo_generator_v13_2_10 axis_infrastructure_v1_1_1 axis_data_fifo_v2_0_13 axi_infrastructure_v1_1_0 axi_vip_v1_1_17 processing_system7_vip_v1_0_19 lib_cdc_v1_0_3 proc_sys_reset_v5_0_15 xlconcat_v2_1_6 lib_pkg_v1_0_4 lib_fifo_v1_0_19 blk_mem_gen_v8_4_8 lib_bmg_v1_0_17 lib_srl_fifo_v1_0_4 axi_datamover_v5_1_33 axi_vdma_v6_3_19 generic_baseblocks_v2_1_2 axi_register_slice_v2_1_31 axi_data_fifo_v2_1_30 axi_crossbar_v2_1_32 axi_lite_ipif_v3_0_4 v_tc_v6_1_14 v_vid_in_axi4s_v4_0_11 v_axi4s_vid_out_v4_0_18 v_tc_v6_2_8 axi_protocol_converter_v2_1_31)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2024.1 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./system.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "C:/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "C:/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "C:/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "C:/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "C:/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "C:/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "C:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "C:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "C:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm $xmvhdl_opts \
  "C:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/system/ipshared/40b8/hdl/LineBuffer.vhd" \
  "../../../bd/system/ipshared/40b8/hdl/AXI_BayerToRGB.vhd" \
  "../../../bd/system/ip/system_AXI_BayerToRGB_1_0/sim/system_AXI_BayerToRGB_1_0.vhd" \
  "../../../bd/system/ipshared/a507/hdl/StoredGammaCoefs.vhd" \
  "../../../bd/system/ipshared/a507/hdl/AXI_GammaCorrection.vhd" \
  "../../../bd/system/ip/system_AXI_GammaCorrection_0_0/sim/system_AXI_GammaCorrection_0_0.vhd" \
  "../../../bd/system/ip/system_DVIClocking_0_0/sim/system_DVIClocking_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_10 $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work fifo_generator_v13_2_10 $xmvhdl_opts \
  "../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_10 $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/sim/cdc_fifo.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/sim/ila_rxclk.vhd" \
  "../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/sim/ila_rxclk_lane.vhd" \
  "../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/sim/ila_vidclk.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work axis_infrastructure_v1_1_1 $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_data_fifo_v2_0_13 $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/sim/line_buffer.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/system/ipshared/b799/hdl/CRC16_behavioral.vhd" \
  "../../../bd/system/ipshared/b799/hdl/DebugLib.vhd" \
  "../../../bd/system/ipshared/b799/hdl/ECC.vhd" \
  "../../../bd/system/ipshared/b799/hdl/SyncAsync.vhd" \
  "../../../bd/system/ipshared/b799/hdl/SyncAsyncReset.vhd" \
  "../../../bd/system/ipshared/b799/hdl/LLP.vhd" \
  "../../../bd/system/ipshared/b799/hdl/SimpleFIFO.vhd" \
  "../../../bd/system/ipshared/b799/hdl/LM.vhd" \
  "../../../bd/system/ipshared/b799/hdl/MIPI_CSI2_Rx.vhd" \
  "../../../bd/system/ipshared/b799/hdl/MIPI_CSI_2_RX_v1_0_S_AXI_LITE.vhd" \
  "../../../bd/system/ipshared/b799/hdl/MIPI_CSI2_RxTop.vhd" \
  "../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0/sim/system_MIPI_CSI_2_RX_0_0.vhd" \
  "../../../bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/sim/ila_sfen_rxclk.vhd" \
  "../../../bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/sim/ila_sfen_refclk.vhd" \
  "../../../bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/sim/ila_scnn_refclk.vhd" \
  "../../../bd/system/ipshared/7858/hdl/DPHY_Pkg.vhd" \
  "../../../bd/system/ipshared/7858/hdl/DebugLib.vhd" \
  "../../../bd/system/ipshared/7858/hdl/HS_Deserializer.vhd" \
  "../../../bd/system/ipshared/7858/hdl/GlitchFilter.vhd" \
  "../../../bd/system/ipshared/7858/hdl/HS_Clocking.vhd" \
  "../../../bd/system/ipshared/7858/hdl/InputBuffer.vhd" \
  "../../../bd/system/ipshared/7858/hdl/DPHY_LaneSFEN.vhd" \
  "../../../bd/system/ipshared/7858/hdl/DPHY_LaneSCNN.vhd" \
  "../../../bd/system/ipshared/7858/hdl/S_AXI_Lite.vhd" \
  "../../../bd/system/ipshared/7858/hdl/MIPI_DPHY_Receiver.vhd" \
  "../../../bd/system/ip/system_MIPI_D_PHY_RX_0_0/sim/system_MIPI_D_PHY_RX_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_17 $xmvlog_opts -sv +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/4d04/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work processing_system7_vip_v1_0_19 $xmvlog_opts -sv +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_processing_system7_0_0/sim/system_processing_system7_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/d57c/src/ClockGen.vhd" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/d57c/src/SyncAsync.vhd" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/d57c/src/SyncAsyncReset.vhd" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/d57c/src/DVI_Constants.vhd" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/d57c/src/OutputSERDES.vhd" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/d57c/src/TMDS_Encoder.vhd" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/d57c/src/rgb2dvi.vhd" \
  "../../../bd/system/ip/system_rgb2dvi_0_0/sim/system_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_3 $xmvhdl_opts \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_15 $xmvhdl_opts \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3a26/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/system/ip/system_rst_clk_wiz_0_50M_0/sim/system_rst_clk_wiz_0_50M_0.vhd" \
  "../../../bd/system/ip/system_rst_vid_clk_dyn_0/sim/system_rst_vid_clk_dyn_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xlconcat_v2_1_6 $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/6120/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_xlconcat_0_0/sim/system_xlconcat_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_pkg_v1_0_4 $xmvhdl_opts \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/8c68/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_fifo_v1_0_19 $xmvhdl_opts \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/0a12/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work blk_mem_gen_v8_4_8 $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/09bd/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_bmg_v1_0_17 $xmvhdl_opts \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3f29/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_srl_fifo_v1_0_4 $xmvhdl_opts \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/1e5a/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_datamover_v5_1_33 $xmvhdl_opts \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/bf20/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work axi_vdma_v6_3_19 $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_vdma_v6_3_19 $xmvhdl_opts \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/system/ip/system_axi_vdma_0_0/sim/system_axi_vdma_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_clk_wiz.v" \
  "../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work generic_baseblocks_v2_1_2 $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/0c28/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_31 $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/92b2/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_data_fifo_v2_1_30 $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/9692/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_crossbar_v2_1_32 $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/e9d8/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_xbar_0/sim/system_xbar_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_lite_ipif_v3_0_4 $xmvhdl_opts \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work v_tc_v6_1_14 $xmvhdl_opts \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/fd54/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work v_vid_in_axi4s_v4_0_11 $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/4705/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work v_axi4s_vid_out_v4_0_18 $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/52cd/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_v_axi4s_vid_out_0_0/sim/system_v_axi4s_vid_out_0_0.v" \
  "../../../bd/system/ip/system_video_dynclk_0/system_video_dynclk_0_mmcm_pll_drp.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_conv_funs_pkg.vhd" \
  "../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_proc_common_pkg.vhd" \
  "../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_ipif_pkg.vhd" \
  "../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_family_support.vhd" \
  "../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_family.vhd" \
  "../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_soft_reset.vhd" \
  "../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_pselect_f.vhd" \
  "../../../bd/system/ip/system_video_dynclk_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_video_dynclk_0_address_decoder.vhd" \
  "../../../bd/system/ip/system_video_dynclk_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_video_dynclk_0_slave_attachment.vhd" \
  "../../../bd/system/ip/system_video_dynclk_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_video_dynclk_0_axi_lite_ipif.vhd" \
  "../../../bd/system/ip/system_video_dynclk_0/system_video_dynclk_0_clk_wiz_drp.vhd" \
  "../../../bd/system/ip/system_video_dynclk_0/system_video_dynclk_0_axi_clk_config.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_video_dynclk_0/system_video_dynclk_0_clk_wiz.v" \
  "../../../bd/system/ip/system_video_dynclk_0/system_video_dynclk_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work v_tc_v6_2_8 $xmvhdl_opts \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/5959/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/system/ip/system_vtg_0/sim/system_vtg_0.vhd" \
  "../../../bd/system/ip/system_multipix_ctrl_0_0/sim/system_multipix_ctrl_0_0.vhd" \
  "../../../bd/system/ip/system_singlepix_ctrl_0_0/sim/system_singlepix_ctrl_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work axi_protocol_converter_v2_1_31 $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3c06/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/b28c/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/a4a8/hdl" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ipshared/3242" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"../../../../pcam_filter.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \
  "../../../bd/system/ip/system_auto_pc_1/sim/system_auto_pc_1.v" \
  "../../../bd/system/ip/system_auto_pc_2/sim/system_auto_pc_2.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/system/sim/system.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.system xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.system -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file


  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log system_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-step]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-reset_log]\n\
Usage: system.sh [-keep_index]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
