
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xoverlay_core.h"

/*
* The configuration table for devices
*/

XOverlay_core_Config XOverlay_core_ConfigTable[XPAR_XOVERLAY_CORE_NUM_INSTANCES] =
{
	{
		XPAR_OVERLAY_CORE_0_DEVICE_ID,
		XPAR_OVERLAY_CORE_0_S_AXI_CTRL_BASEADDR
	}
};


