// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stream_in_TVALID,
        stream_out_TREADY,
        mul_ln74,
        width,
        add_i_i486,
        add_i_i458,
        y,
        add_i_i163,
        add_i_i135,
        y_1,
        y_pos,
        add_i_i564,
        stream_in_TDATA,
        stream_in_TREADY,
        stream_in_TKEEP,
        stream_in_TSTRB,
        stream_in_TUSER,
        stream_in_TLAST,
        stream_in_TID,
        stream_in_TDEST,
        x_pos,
        add_i_i533,
        start_x,
        char_x,
        char_x_2,
        enable,
        stream_out_TDATA,
        stream_out_TVALID,
        stream_out_TKEEP,
        stream_out_TSTRB,
        stream_out_TUSER,
        stream_out_TLAST,
        stream_out_TID,
        stream_out_TDEST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   stream_in_TVALID;
input   stream_out_TREADY;
input  [31:0] mul_ln74;
input  [15:0] width;
input  [16:0] add_i_i486;
input  [16:0] add_i_i458;
input  [15:0] y;
input  [16:0] add_i_i163;
input  [16:0] add_i_i135;
input  [15:0] y_1;
input  [15:0] y_pos;
input  [16:0] add_i_i564;
input  [23:0] stream_in_TDATA;
output   stream_in_TREADY;
input  [2:0] stream_in_TKEEP;
input  [2:0] stream_in_TSTRB;
input  [0:0] stream_in_TUSER;
input  [0:0] stream_in_TLAST;
input  [0:0] stream_in_TID;
input  [0:0] stream_in_TDEST;
input  [15:0] x_pos;
input  [16:0] add_i_i533;
input  [15:0] start_x;
input  [15:0] char_x;
input  [15:0] char_x_2;
input  [0:0] enable;
output  [23:0] stream_out_TDATA;
output   stream_out_TVALID;
output  [2:0] stream_out_TKEEP;
output  [2:0] stream_out_TSTRB;
output  [0:0] stream_out_TUSER;
output  [0:0] stream_out_TLAST;
output  [0:0] stream_out_TID;
output  [0:0] stream_out_TDEST;

reg ap_idle;
reg stream_in_TREADY;
reg stream_out_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln105_fu_437_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] p_ZL8font_5x7_3_3_address0;
wire   [6:0] p_ZL8font_5x7_3_3_q0;
wire   [2:0] p_ZL8font_5x7_2_1_address0;
wire   [6:0] p_ZL8font_5x7_2_1_q0;
wire   [2:0] p_ZL8font_5x7_2_1_address1;
wire   [6:0] p_ZL8font_5x7_2_1_q1;
wire   [2:0] p_ZL8font_5x7_2_0_address0;
wire   [6:0] p_ZL8font_5x7_2_0_q0;
wire   [2:0] p_ZL8font_5x7_4_1_address0;
wire   [6:0] p_ZL8font_5x7_4_1_q0;
wire   [2:0] p_ZL8font_5x7_5_2_address0;
wire   [6:0] p_ZL8font_5x7_5_2_q0;
wire   [2:0] p_ZL8font_5x7_0_0_address0;
wire   [5:0] p_ZL8font_5x7_0_0_q0;
wire   [2:0] p_ZL8font_5x7_1_3_address0;
wire   [1:0] p_ZL8font_5x7_1_3_q0;
reg    stream_in_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    stream_out_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [23:0] pixel_in_data_reg_1259;
reg   [23:0] pixel_in_data_reg_1259_pp0_iter1_reg;
reg   [23:0] pixel_in_data_reg_1259_pp0_iter2_reg;
reg   [23:0] pixel_in_data_reg_1259_pp0_iter3_reg;
reg   [2:0] pixel_in_keep_reg_1266;
reg   [2:0] pixel_in_keep_reg_1266_pp0_iter1_reg;
reg   [2:0] pixel_in_keep_reg_1266_pp0_iter2_reg;
reg   [2:0] pixel_in_keep_reg_1266_pp0_iter3_reg;
reg   [0:0] pixel_in_user_reg_1271;
reg   [0:0] pixel_in_user_reg_1271_pp0_iter1_reg;
reg   [0:0] pixel_in_user_reg_1271_pp0_iter2_reg;
reg   [0:0] pixel_in_user_reg_1271_pp0_iter3_reg;
reg   [0:0] pixel_in_last_reg_1276;
reg   [0:0] pixel_in_last_reg_1276_pp0_iter1_reg;
reg   [0:0] pixel_in_last_reg_1276_pp0_iter2_reg;
reg   [0:0] pixel_in_last_reg_1276_pp0_iter3_reg;
reg   [7:0] r_reg_1281;
reg   [7:0] r_reg_1281_pp0_iter1_reg;
reg   [7:0] r_reg_1281_pp0_iter2_reg;
reg   [7:0] r_reg_1281_pp0_iter3_reg;
reg   [7:0] g_reg_1287;
reg   [7:0] g_reg_1287_pp0_iter1_reg;
reg   [7:0] g_reg_1287_pp0_iter2_reg;
reg   [7:0] g_reg_1287_pp0_iter3_reg;
wire   [7:0] b_fu_485_p1;
reg   [7:0] b_reg_1293;
reg   [7:0] b_reg_1293_pp0_iter1_reg;
reg   [7:0] b_reg_1293_pp0_iter2_reg;
reg   [7:0] b_reg_1293_pp0_iter3_reg;
wire   [15:0] select_ln105_fu_505_p3;
reg   [15:0] select_ln105_reg_1299;
wire   [15:0] select_ln105_1_fu_519_p3;
reg   [15:0] select_ln105_1_reg_1310;
wire   [0:0] ult_fu_546_p2;
reg   [0:0] ult_reg_1318;
reg   [0:0] ult_reg_1318_pp0_iter3_reg;
wire   [0:0] cmp_i435_fu_551_p2;
reg   [0:0] cmp_i435_reg_1323;
reg   [0:0] cmp_i435_reg_1323_pp0_iter3_reg;
wire   [15:0] rel_y_fu_556_p2;
reg   [15:0] rel_y_reg_1328;
wire   [0:0] ult39_fu_560_p2;
reg   [0:0] ult39_reg_1334;
reg   [0:0] ult39_reg_1334_pp0_iter3_reg;
wire   [0:0] cmp_i112_fu_565_p2;
reg   [0:0] cmp_i112_reg_1339;
reg   [0:0] cmp_i112_reg_1339_pp0_iter3_reg;
wire   [15:0] rel_y_1_fu_570_p2;
reg   [15:0] rel_y_1_reg_1344;
wire   [0:0] and_ln122_1_fu_619_p2;
reg   [0:0] and_ln122_1_reg_1350;
reg   [0:0] and_ln122_1_reg_1350_pp0_iter3_reg;
wire   [0:0] icmp_ln49_fu_629_p2;
reg   [0:0] icmp_ln49_reg_1357;
reg   [0:0] icmp_ln49_reg_1357_pp0_iter3_reg;
wire   [0:0] icmp_ln49_1_fu_645_p2;
reg   [0:0] icmp_ln49_1_reg_1368;
reg   [0:0] icmp_ln49_1_reg_1368_pp0_iter3_reg;
wire   [0:0] icmp_ln49_2_fu_661_p2;
reg   [0:0] icmp_ln49_2_reg_1379;
reg   [0:0] icmp_ln49_2_reg_1379_pp0_iter3_reg;
wire   [15:0] rel_x_3_fu_678_p2;
reg   [15:0] rel_x_3_reg_1390;
wire   [15:0] rel_x_4_fu_693_p2;
reg   [15:0] rel_x_4_reg_1400;
wire   [6:0] empty_fu_712_p1;
reg   [6:0] empty_reg_1425;
wire   [6:0] empty_18_fu_725_p1;
reg   [6:0] empty_18_reg_1430;
wire   [0:0] cmp_i_i17_i_i319_not_fu_729_p2;
reg   [0:0] cmp_i_i17_i_i319_not_reg_1435;
wire   [0:0] cmp_i_i17_i_i_not_fu_734_p2;
reg   [0:0] cmp_i_i17_i_i_not_reg_1444;
reg   [6:0] col_2_reg_1451;
wire   [0:0] icmp_ln49_3_fu_751_p2;
reg   [0:0] icmp_ln49_3_reg_1456;
wire   [0:0] icmp_ln49_4_fu_762_p2;
reg   [0:0] icmp_ln49_4_reg_1461;
wire   [0:0] icmp_ln52_fu_773_p2;
reg   [0:0] icmp_ln52_reg_1466;
wire   [0:0] icmp_ln52_1_fu_779_p2;
reg   [0:0] icmp_ln52_1_reg_1471;
wire   [0:0] icmp_ln52_3_fu_785_p2;
reg   [0:0] icmp_ln52_3_reg_1476;
wire   [0:0] icmp_ln52_4_fu_791_p2;
reg   [0:0] icmp_ln52_4_reg_1481;
reg   [6:0] col_5_reg_1486;
wire   [0:0] icmp_ln52_6_fu_817_p2;
reg   [0:0] icmp_ln52_6_reg_1491;
wire   [0:0] icmp_ln52_7_fu_823_p2;
reg   [0:0] icmp_ln52_7_reg_1496;
wire   [63:0] zext_ln51_fu_635_p1;
wire   [63:0] zext_ln51_1_fu_651_p1;
wire   [63:0] zext_ln51_2_fu_667_p1;
wire   [63:0] zext_ln51_3_fu_683_p1;
wire   [63:0] zext_ln51_4_fu_698_p1;
reg   [15:0] pixel_x_fu_162;
wire   [15:0] add_ln106_fu_527_p2;
wire    ap_loop_init;
reg   [15:0] row_fu_166;
reg   [31:0] indvar_flatten_fu_170;
wire   [31:0] add_ln105_fu_443_p2;
reg   [31:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage0_01001;
reg    p_ZL8font_5x7_3_3_ce0_local;
reg    p_ZL8font_5x7_2_1_ce1_local;
reg    p_ZL8font_5x7_2_1_ce0_local;
reg    p_ZL8font_5x7_2_0_ce0_local;
reg    p_ZL8font_5x7_4_1_ce0_local;
reg    p_ZL8font_5x7_5_2_ce0_local;
reg    p_ZL8font_5x7_0_0_ce0_local;
reg    p_ZL8font_5x7_1_3_ce0_local;
wire   [0:0] icmp_ln106_fu_500_p2;
wire   [15:0] add_ln105_1_fu_513_p2;
wire   [16:0] row_cast_fu_543_p1;
wire   [0:0] ult41_fu_574_p2;
wire   [0:0] icmp_ln123_fu_589_p2;
wire   [16:0] zext_ln123_fu_599_p1;
wire   [0:0] rev42_fu_578_p2;
wire   [0:0] xor_ln123_fu_593_p2;
wire   [0:0] notrhs_fu_584_p2;
wire   [0:0] icmp_ln123_1_fu_602_p2;
wire   [0:0] and_ln122_2_fu_613_p2;
wire   [0:0] and_ln122_fu_607_p2;
wire   [15:0] rel_x_fu_625_p2;
wire   [15:0] rel_x_1_fu_641_p2;
wire   [15:0] rel_x_2_fu_657_p2;
wire   [15:0] char_x_4_fu_673_p2;
wire   [15:0] char_x_5_fu_688_p2;
wire   [31:0] sh_prom_i_i327_fu_703_p1;
wire   [31:0] shl_i_i328_fu_706_p2;
wire   [31:0] sh_prom_i_i_fu_716_p1;
wire   [31:0] shl_i_i_fu_719_p2;
wire   [6:0] and_ln52_fu_739_p2;
wire   [6:0] and_ln52_1_fu_745_p2;
wire   [6:0] and_ln52_3_fu_756_p2;
wire   [6:0] and_ln52_4_fu_767_p2;
wire  signed [6:0] sext_ln51_fu_797_p1;
wire  signed [6:0] sext_ln51_1_fu_807_p1;
wire   [6:0] and_ln52_6_fu_801_p2;
wire   [6:0] and_ln52_7_fu_811_p2;
wire   [0:0] rev40_fu_834_p2;
wire   [6:0] r_1_fu_844_p4;
wire   [6:0] g_1_fu_857_p4;
wire   [6:0] b_1_fu_870_p4;
wire   [7:0] zext_ln126_fu_866_p1;
wire   [7:0] zext_ln125_fu_853_p1;
wire   [7:0] zext_ln127_fu_879_p1;
wire   [0:0] or_ln49_fu_901_p2;
wire   [0:0] xor_ln49_fu_925_p2;
wire   [0:0] or_ln49_1_fu_905_p2;
wire   [0:0] xor_ln49_1_fu_936_p2;
wire   [0:0] or_ln49_2_fu_909_p2;
wire   [6:0] and_ln52_2_fu_913_p2;
wire   [0:0] icmp_ln52_2_fu_953_p2;
wire   [0:0] xor_ln49_2_fu_947_p2;
wire   [0:0] or_ln49_3_fu_917_p2;
wire   [0:0] xor_ln49_3_fu_965_p2;
wire   [0:0] or_ln49_4_fu_921_p2;
wire   [0:0] xor_ln49_4_fu_976_p2;
wire   [0:0] and_ln52_8_fu_931_p2;
wire   [0:0] and_ln52_9_fu_942_p2;
wire   [0:0] and_ln52_11_fu_971_p2;
wire   [0:0] and_ln52_12_fu_982_p2;
wire   [0:0] or_ln52_1_fu_993_p2;
wire   [0:0] and_ln52_10_fu_959_p2;
wire   [0:0] or_ln52_2_fu_999_p2;
wire   [0:0] or_ln52_fu_987_p2;
wire   [0:0] or_ln52_3_fu_1005_p2;
wire   [0:0] and_ln52_13_fu_1011_p2;
wire   [0:0] rev_fu_829_p2;
wire   [0:0] or_ln49_5_fu_1022_p2;
wire   [6:0] and_ln52_5_fu_1026_p2;
wire   [0:0] icmp_ln52_5_fu_1044_p2;
wire   [0:0] xor_ln49_5_fu_1038_p2;
wire   [0:0] or_ln49_6_fu_1030_p2;
wire   [0:0] xor_ln49_6_fu_1056_p2;
wire   [0:0] or_ln49_7_fu_1034_p2;
wire   [0:0] xor_ln49_7_fu_1067_p2;
wire   [0:0] and_ln52_16_fu_1062_p2;
wire   [0:0] and_ln52_17_fu_1073_p2;
wire   [0:0] or_ln52_4_fu_1078_p2;
wire   [0:0] and_ln52_15_fu_1050_p2;
wire   [0:0] spec_select1222_fu_839_p2;
wire   [0:0] empty_20_fu_1084_p2;
wire   [0:0] draw_pixel_fu_1016_p2;
wire   [0:0] draw_pixel_1_fu_1090_p2;
wire   [0:0] draw_pixel_2_fu_1096_p2;
wire   [7:0] select_ln122_1_fu_889_p3;
wire   [7:0] select_ln122_fu_883_p3;
wire   [7:0] b_3_fu_895_p3;
wire   [7:0] r_3_fu_1102_p3;
wire   [7:0] g_3_fu_1110_p3;
wire   [7:0] b_4_fu_1118_p3;
wire   [7:0] r_2_fu_1126_p3;
wire   [7:0] g_2_fu_1132_p3;
wire   [7:0] b_2_fu_1138_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 pixel_x_fu_162 = 16'd0;
#0 row_fu_166 = 16'd0;
#0 indvar_flatten_fu_170 = 32'd0;
#0 ap_done_reg = 1'b0;
end

overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_3_3_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
p_ZL8font_5x7_3_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8font_5x7_3_3_address0),
    .ce0(p_ZL8font_5x7_3_3_ce0_local),
    .q0(p_ZL8font_5x7_3_3_q0)
);

overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_2_1_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
p_ZL8font_5x7_2_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8font_5x7_2_1_address0),
    .ce0(p_ZL8font_5x7_2_1_ce0_local),
    .q0(p_ZL8font_5x7_2_1_q0),
    .address1(p_ZL8font_5x7_2_1_address1),
    .ce1(p_ZL8font_5x7_2_1_ce1_local),
    .q1(p_ZL8font_5x7_2_1_q1)
);

overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_2_0_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
p_ZL8font_5x7_2_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8font_5x7_2_0_address0),
    .ce0(p_ZL8font_5x7_2_0_ce0_local),
    .q0(p_ZL8font_5x7_2_0_q0)
);

overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_4_1_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
p_ZL8font_5x7_4_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8font_5x7_4_1_address0),
    .ce0(p_ZL8font_5x7_4_1_ce0_local),
    .q0(p_ZL8font_5x7_4_1_q0)
);

overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_5_2_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
p_ZL8font_5x7_5_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8font_5x7_5_2_address0),
    .ce0(p_ZL8font_5x7_5_2_ce0_local),
    .q0(p_ZL8font_5x7_5_2_q0)
);

overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_0_0_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
p_ZL8font_5x7_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8font_5x7_0_0_address0),
    .ce0(p_ZL8font_5x7_0_0_ce0_local),
    .q0(p_ZL8font_5x7_0_0_q0)
);

overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH_p_ZL8font_5x7_1_3_ROM_AUTO_1R #(
    .DataWidth( 2 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
p_ZL8font_5x7_1_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8font_5x7_1_3_address0),
    .ce0(p_ZL8font_5x7_1_3_ce0_local),
    .q0(p_ZL8font_5x7_1_3_q0)
);

overlay_core_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln105_fu_437_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            indvar_flatten_fu_170 <= add_ln105_fu_443_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_170 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            pixel_x_fu_162 <= 16'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            pixel_x_fu_162 <= add_ln106_fu_527_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            row_fu_166 <= 16'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            row_fu_166 <= select_ln105_1_fu_519_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln122_1_reg_1350 <= and_ln122_1_fu_619_p2;
        and_ln122_1_reg_1350_pp0_iter3_reg <= and_ln122_1_reg_1350;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        b_reg_1293_pp0_iter2_reg <= b_reg_1293_pp0_iter1_reg;
        b_reg_1293_pp0_iter3_reg <= b_reg_1293_pp0_iter2_reg;
        cmp_i112_reg_1339 <= cmp_i112_fu_565_p2;
        cmp_i112_reg_1339_pp0_iter3_reg <= cmp_i112_reg_1339;
        cmp_i435_reg_1323 <= cmp_i435_fu_551_p2;
        cmp_i435_reg_1323_pp0_iter3_reg <= cmp_i435_reg_1323;
        cmp_i_i17_i_i319_not_reg_1435 <= cmp_i_i17_i_i319_not_fu_729_p2;
        cmp_i_i17_i_i_not_reg_1444 <= cmp_i_i17_i_i_not_fu_734_p2;
        col_2_reg_1451 <= p_ZL8font_5x7_2_0_q0;
        col_5_reg_1486 <= p_ZL8font_5x7_5_2_q0;
        empty_18_reg_1430 <= empty_18_fu_725_p1;
        empty_reg_1425 <= empty_fu_712_p1;
        g_reg_1287_pp0_iter2_reg <= g_reg_1287_pp0_iter1_reg;
        g_reg_1287_pp0_iter3_reg <= g_reg_1287_pp0_iter2_reg;
        icmp_ln49_1_reg_1368 <= icmp_ln49_1_fu_645_p2;
        icmp_ln49_1_reg_1368_pp0_iter3_reg <= icmp_ln49_1_reg_1368;
        icmp_ln49_2_reg_1379 <= icmp_ln49_2_fu_661_p2;
        icmp_ln49_2_reg_1379_pp0_iter3_reg <= icmp_ln49_2_reg_1379;
        icmp_ln49_3_reg_1456 <= icmp_ln49_3_fu_751_p2;
        icmp_ln49_4_reg_1461 <= icmp_ln49_4_fu_762_p2;
        icmp_ln49_reg_1357 <= icmp_ln49_fu_629_p2;
        icmp_ln49_reg_1357_pp0_iter3_reg <= icmp_ln49_reg_1357;
        icmp_ln52_1_reg_1471 <= icmp_ln52_1_fu_779_p2;
        icmp_ln52_3_reg_1476 <= icmp_ln52_3_fu_785_p2;
        icmp_ln52_4_reg_1481 <= icmp_ln52_4_fu_791_p2;
        icmp_ln52_6_reg_1491 <= icmp_ln52_6_fu_817_p2;
        icmp_ln52_7_reg_1496 <= icmp_ln52_7_fu_823_p2;
        icmp_ln52_reg_1466 <= icmp_ln52_fu_773_p2;
        pixel_in_data_reg_1259_pp0_iter2_reg <= pixel_in_data_reg_1259_pp0_iter1_reg;
        pixel_in_data_reg_1259_pp0_iter3_reg <= pixel_in_data_reg_1259_pp0_iter2_reg;
        pixel_in_keep_reg_1266_pp0_iter2_reg <= pixel_in_keep_reg_1266_pp0_iter1_reg;
        pixel_in_keep_reg_1266_pp0_iter3_reg <= pixel_in_keep_reg_1266_pp0_iter2_reg;
        pixel_in_last_reg_1276_pp0_iter2_reg <= pixel_in_last_reg_1276_pp0_iter1_reg;
        pixel_in_last_reg_1276_pp0_iter3_reg <= pixel_in_last_reg_1276_pp0_iter2_reg;
        pixel_in_user_reg_1271_pp0_iter2_reg <= pixel_in_user_reg_1271_pp0_iter1_reg;
        pixel_in_user_reg_1271_pp0_iter3_reg <= pixel_in_user_reg_1271_pp0_iter2_reg;
        r_reg_1281_pp0_iter2_reg <= r_reg_1281_pp0_iter1_reg;
        r_reg_1281_pp0_iter3_reg <= r_reg_1281_pp0_iter2_reg;
        rel_x_3_reg_1390 <= rel_x_3_fu_678_p2;
        rel_x_4_reg_1400 <= rel_x_4_fu_693_p2;
        rel_y_1_reg_1344 <= rel_y_1_fu_570_p2;
        rel_y_reg_1328 <= rel_y_fu_556_p2;
        ult39_reg_1334 <= ult39_fu_560_p2;
        ult39_reg_1334_pp0_iter3_reg <= ult39_reg_1334;
        ult_reg_1318 <= ult_fu_546_p2;
        ult_reg_1318_pp0_iter3_reg <= ult_reg_1318;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        b_reg_1293 <= b_fu_485_p1;
        b_reg_1293_pp0_iter1_reg <= b_reg_1293;
        g_reg_1287 <= {{stream_in_TDATA[15:8]}};
        g_reg_1287_pp0_iter1_reg <= g_reg_1287;
        pixel_in_data_reg_1259 <= stream_in_TDATA;
        pixel_in_data_reg_1259_pp0_iter1_reg <= pixel_in_data_reg_1259;
        pixel_in_keep_reg_1266 <= stream_in_TKEEP;
        pixel_in_keep_reg_1266_pp0_iter1_reg <= pixel_in_keep_reg_1266;
        pixel_in_last_reg_1276 <= stream_in_TLAST;
        pixel_in_last_reg_1276_pp0_iter1_reg <= pixel_in_last_reg_1276;
        pixel_in_user_reg_1271 <= stream_in_TUSER;
        pixel_in_user_reg_1271_pp0_iter1_reg <= pixel_in_user_reg_1271;
        r_reg_1281 <= {{stream_in_TDATA[23:16]}};
        r_reg_1281_pp0_iter1_reg <= r_reg_1281;
        select_ln105_1_reg_1310 <= select_ln105_1_fu_519_p3;
        select_ln105_reg_1299 <= select_ln105_fu_505_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln105_fu_437_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 32'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_170;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL8font_5x7_0_0_ce0_local = 1'b1;
    end else begin
        p_ZL8font_5x7_0_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL8font_5x7_1_3_ce0_local = 1'b1;
    end else begin
        p_ZL8font_5x7_1_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL8font_5x7_2_0_ce0_local = 1'b1;
    end else begin
        p_ZL8font_5x7_2_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL8font_5x7_2_1_ce0_local = 1'b1;
    end else begin
        p_ZL8font_5x7_2_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL8font_5x7_2_1_ce1_local = 1'b1;
    end else begin
        p_ZL8font_5x7_2_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL8font_5x7_3_3_ce0_local = 1'b1;
    end else begin
        p_ZL8font_5x7_3_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL8font_5x7_4_1_ce0_local = 1'b1;
    end else begin
        p_ZL8font_5x7_4_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL8font_5x7_5_2_ce0_local = 1'b1;
    end else begin
        p_ZL8font_5x7_5_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln105_fu_437_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_TDATA_blk_n = stream_in_TVALID;
    end else begin
        stream_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln105_fu_437_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_TREADY = 1'b1;
    end else begin
        stream_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        stream_out_TDATA_blk_n = stream_out_TREADY;
    end else begin
        stream_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        stream_out_TVALID = 1'b1;
    end else begin
        stream_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln105_1_fu_513_p2 = (row_fu_166 + 16'd1);

assign add_ln105_fu_443_p2 = (ap_sig_allocacmp_indvar_flatten_load + 32'd1);

assign add_ln106_fu_527_p2 = (select_ln105_fu_505_p3 + 16'd1);

assign and_ln122_1_fu_619_p2 = (and_ln122_fu_607_p2 & and_ln122_2_fu_613_p2);

assign and_ln122_2_fu_613_p2 = (notrhs_fu_584_p2 & icmp_ln123_1_fu_602_p2);

assign and_ln122_fu_607_p2 = (xor_ln123_fu_593_p2 & rev42_fu_578_p2);

assign and_ln52_10_fu_959_p2 = (xor_ln49_2_fu_947_p2 & icmp_ln52_2_fu_953_p2);

assign and_ln52_11_fu_971_p2 = (xor_ln49_3_fu_965_p2 & icmp_ln52_3_reg_1476);

assign and_ln52_12_fu_982_p2 = (xor_ln49_4_fu_976_p2 & icmp_ln52_4_reg_1481);

assign and_ln52_13_fu_1011_p2 = (or_ln52_3_fu_1005_p2 & cmp_i435_reg_1323_pp0_iter3_reg);

assign and_ln52_15_fu_1050_p2 = (xor_ln49_5_fu_1038_p2 & icmp_ln52_5_fu_1044_p2);

assign and_ln52_16_fu_1062_p2 = (xor_ln49_6_fu_1056_p2 & icmp_ln52_6_reg_1491);

assign and_ln52_17_fu_1073_p2 = (xor_ln49_7_fu_1067_p2 & icmp_ln52_7_reg_1496);

assign and_ln52_1_fu_745_p2 = (p_ZL8font_5x7_2_1_q1 & empty_fu_712_p1);

assign and_ln52_2_fu_913_p2 = (empty_reg_1425 & col_2_reg_1451);

assign and_ln52_3_fu_756_p2 = (p_ZL8font_5x7_4_1_q0 & empty_fu_712_p1);

assign and_ln52_4_fu_767_p2 = (p_ZL8font_5x7_2_1_q0 & empty_fu_712_p1);

assign and_ln52_5_fu_1026_p2 = (empty_18_reg_1430 & col_5_reg_1486);

assign and_ln52_6_fu_801_p2 = (sext_ln51_fu_797_p1 & empty_18_fu_725_p1);

assign and_ln52_7_fu_811_p2 = (sext_ln51_1_fu_807_p1 & empty_18_fu_725_p1);

assign and_ln52_8_fu_931_p2 = (xor_ln49_fu_925_p2 & icmp_ln52_reg_1466);

assign and_ln52_9_fu_942_p2 = (xor_ln49_1_fu_936_p2 & icmp_ln52_1_reg_1471);

assign and_ln52_fu_739_p2 = (p_ZL8font_5x7_3_3_q0 & empty_fu_712_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & ((stream_out_TREADY == 1'b0) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & ((stream_out_TREADY == 1'b0) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((icmp_ln105_fu_437_p2 == 1'd0) & (stream_in_TVALID == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = (stream_out_TREADY == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b_1_fu_870_p4 = {{pixel_in_data_reg_1259_pp0_iter3_reg[7:1]}};

assign b_2_fu_1138_p3 = ((enable[0:0] == 1'b1) ? b_4_fu_1118_p3 : b_reg_1293_pp0_iter3_reg);

assign b_3_fu_895_p3 = ((and_ln122_1_reg_1350_pp0_iter3_reg[0:0] == 1'b1) ? zext_ln127_fu_879_p1 : b_reg_1293_pp0_iter3_reg);

assign b_4_fu_1118_p3 = ((draw_pixel_2_fu_1096_p2[0:0] == 1'b1) ? 8'd255 : b_3_fu_895_p3);

assign b_fu_485_p1 = stream_in_TDATA[7:0];

assign char_x_4_fu_673_p2 = ($signed(16'd65513) - $signed(x_pos));

assign char_x_5_fu_688_p2 = ($signed(16'd65507) - $signed(x_pos));

assign cmp_i112_fu_565_p2 = ((add_i_i135 > row_cast_fu_543_p1) ? 1'b1 : 1'b0);

assign cmp_i435_fu_551_p2 = ((add_i_i458 > row_cast_fu_543_p1) ? 1'b1 : 1'b0);

assign cmp_i_i17_i_i319_not_fu_729_p2 = ((rel_y_reg_1328 > 16'd6) ? 1'b1 : 1'b0);

assign cmp_i_i17_i_i_not_fu_734_p2 = ((rel_y_1_reg_1344 > 16'd6) ? 1'b1 : 1'b0);

assign draw_pixel_1_fu_1090_p2 = (spec_select1222_fu_839_p2 & empty_20_fu_1084_p2);

assign draw_pixel_2_fu_1096_p2 = (draw_pixel_fu_1016_p2 | draw_pixel_1_fu_1090_p2);

assign draw_pixel_fu_1016_p2 = (rev_fu_829_p2 & and_ln52_13_fu_1011_p2);

assign empty_18_fu_725_p1 = shl_i_i_fu_719_p2[6:0];

assign empty_20_fu_1084_p2 = (or_ln52_4_fu_1078_p2 | and_ln52_15_fu_1050_p2);

assign empty_fu_712_p1 = shl_i_i328_fu_706_p2[6:0];

assign g_1_fu_857_p4 = {{pixel_in_data_reg_1259_pp0_iter3_reg[15:9]}};

assign g_2_fu_1132_p3 = ((enable[0:0] == 1'b1) ? g_3_fu_1110_p3 : g_reg_1287_pp0_iter3_reg);

assign g_3_fu_1110_p3 = ((draw_pixel_2_fu_1096_p2[0:0] == 1'b1) ? 8'd255 : select_ln122_fu_883_p3);

assign icmp_ln105_fu_437_p2 = ((ap_sig_allocacmp_indvar_flatten_load == mul_ln74) ? 1'b1 : 1'b0);

assign icmp_ln106_fu_500_p2 = ((pixel_x_fu_162 == width) ? 1'b1 : 1'b0);

assign icmp_ln123_1_fu_602_p2 = ((add_i_i533 > zext_ln123_fu_599_p1) ? 1'b1 : 1'b0);

assign icmp_ln123_fu_589_p2 = ((select_ln105_reg_1299 < x_pos) ? 1'b1 : 1'b0);

assign icmp_ln49_1_fu_645_p2 = ((rel_x_1_fu_641_p2 > 16'd4) ? 1'b1 : 1'b0);

assign icmp_ln49_2_fu_661_p2 = ((rel_x_2_fu_657_p2 > 16'd4) ? 1'b1 : 1'b0);

assign icmp_ln49_3_fu_751_p2 = ((rel_x_3_reg_1390 > 16'd4) ? 1'b1 : 1'b0);

assign icmp_ln49_4_fu_762_p2 = ((rel_x_4_reg_1400 > 16'd4) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_629_p2 = ((rel_x_fu_625_p2 > 16'd4) ? 1'b1 : 1'b0);

assign icmp_ln52_1_fu_779_p2 = ((and_ln52_1_fu_745_p2 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_2_fu_953_p2 = ((and_ln52_2_fu_913_p2 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_3_fu_785_p2 = ((and_ln52_3_fu_756_p2 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_4_fu_791_p2 = ((and_ln52_4_fu_767_p2 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_5_fu_1044_p2 = ((and_ln52_5_fu_1026_p2 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_6_fu_817_p2 = ((and_ln52_6_fu_801_p2 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_7_fu_823_p2 = ((and_ln52_7_fu_811_p2 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_773_p2 = ((and_ln52_fu_739_p2 != 7'd0) ? 1'b1 : 1'b0);

assign notrhs_fu_584_p2 = ((add_i_i564 > row_cast_fu_543_p1) ? 1'b1 : 1'b0);

assign or_ln49_1_fu_905_p2 = (icmp_ln49_1_reg_1368_pp0_iter3_reg | cmp_i_i17_i_i319_not_reg_1435);

assign or_ln49_2_fu_909_p2 = (icmp_ln49_2_reg_1379_pp0_iter3_reg | cmp_i_i17_i_i319_not_reg_1435);

assign or_ln49_3_fu_917_p2 = (icmp_ln49_3_reg_1456 | cmp_i_i17_i_i319_not_reg_1435);

assign or_ln49_4_fu_921_p2 = (icmp_ln49_4_reg_1461 | cmp_i_i17_i_i319_not_reg_1435);

assign or_ln49_5_fu_1022_p2 = (icmp_ln49_reg_1357_pp0_iter3_reg | cmp_i_i17_i_i_not_reg_1444);

assign or_ln49_6_fu_1030_p2 = (icmp_ln49_1_reg_1368_pp0_iter3_reg | cmp_i_i17_i_i_not_reg_1444);

assign or_ln49_7_fu_1034_p2 = (icmp_ln49_2_reg_1379_pp0_iter3_reg | cmp_i_i17_i_i_not_reg_1444);

assign or_ln49_fu_901_p2 = (icmp_ln49_reg_1357_pp0_iter3_reg | cmp_i_i17_i_i319_not_reg_1435);

assign or_ln52_1_fu_993_p2 = (and_ln52_12_fu_982_p2 | and_ln52_11_fu_971_p2);

assign or_ln52_2_fu_999_p2 = (or_ln52_1_fu_993_p2 | and_ln52_10_fu_959_p2);

assign or_ln52_3_fu_1005_p2 = (or_ln52_fu_987_p2 | or_ln52_2_fu_999_p2);

assign or_ln52_4_fu_1078_p2 = (and_ln52_17_fu_1073_p2 | and_ln52_16_fu_1062_p2);

assign or_ln52_fu_987_p2 = (and_ln52_9_fu_942_p2 | and_ln52_8_fu_931_p2);

assign p_ZL8font_5x7_0_0_address0 = zext_ln51_1_fu_651_p1;

assign p_ZL8font_5x7_1_3_address0 = zext_ln51_2_fu_667_p1;

assign p_ZL8font_5x7_2_0_address0 = zext_ln51_2_fu_667_p1;

assign p_ZL8font_5x7_2_1_address0 = zext_ln51_4_fu_698_p1;

assign p_ZL8font_5x7_2_1_address1 = zext_ln51_1_fu_651_p1;

assign p_ZL8font_5x7_3_3_address0 = zext_ln51_fu_635_p1;

assign p_ZL8font_5x7_4_1_address0 = zext_ln51_3_fu_683_p1;

assign p_ZL8font_5x7_5_2_address0 = zext_ln51_fu_635_p1;

assign r_1_fu_844_p4 = {{pixel_in_data_reg_1259_pp0_iter3_reg[23:17]}};

assign r_2_fu_1126_p3 = ((enable[0:0] == 1'b1) ? r_3_fu_1102_p3 : r_reg_1281_pp0_iter3_reg);

assign r_3_fu_1102_p3 = ((draw_pixel_2_fu_1096_p2[0:0] == 1'b1) ? 8'd255 : select_ln122_1_fu_889_p3);

assign rel_x_1_fu_641_p2 = (select_ln105_reg_1299 - char_x);

assign rel_x_2_fu_657_p2 = (select_ln105_reg_1299 - char_x_2);

assign rel_x_3_fu_678_p2 = (select_ln105_reg_1299 + char_x_4_fu_673_p2);

assign rel_x_4_fu_693_p2 = (select_ln105_reg_1299 + char_x_5_fu_688_p2);

assign rel_x_fu_625_p2 = (select_ln105_reg_1299 - start_x);

assign rel_y_1_fu_570_p2 = (select_ln105_1_reg_1310 + y_1);

assign rel_y_fu_556_p2 = (select_ln105_1_reg_1310 + y);

assign rev40_fu_834_p2 = (ult39_reg_1334_pp0_iter3_reg ^ 1'd1);

assign rev42_fu_578_p2 = (ult41_fu_574_p2 ^ 1'd1);

assign rev_fu_829_p2 = (ult_reg_1318_pp0_iter3_reg ^ 1'd1);

assign row_cast_fu_543_p1 = select_ln105_1_reg_1310;

assign select_ln105_1_fu_519_p3 = ((icmp_ln106_fu_500_p2[0:0] == 1'b1) ? add_ln105_1_fu_513_p2 : row_fu_166);

assign select_ln105_fu_505_p3 = ((icmp_ln106_fu_500_p2[0:0] == 1'b1) ? 16'd0 : pixel_x_fu_162);

assign select_ln122_1_fu_889_p3 = ((and_ln122_1_reg_1350_pp0_iter3_reg[0:0] == 1'b1) ? zext_ln125_fu_853_p1 : r_reg_1281_pp0_iter3_reg);

assign select_ln122_fu_883_p3 = ((and_ln122_1_reg_1350_pp0_iter3_reg[0:0] == 1'b1) ? zext_ln126_fu_866_p1 : g_reg_1287_pp0_iter3_reg);

assign sext_ln51_1_fu_807_p1 = $signed(p_ZL8font_5x7_1_3_q0);

assign sext_ln51_fu_797_p1 = $signed(p_ZL8font_5x7_0_0_q0);

assign sh_prom_i_i327_fu_703_p1 = rel_y_reg_1328;

assign sh_prom_i_i_fu_716_p1 = rel_y_1_reg_1344;

assign shl_i_i328_fu_706_p2 = 32'd1 << sh_prom_i_i327_fu_703_p1;

assign shl_i_i_fu_719_p2 = 32'd1 << sh_prom_i_i_fu_716_p1;

assign spec_select1222_fu_839_p2 = (rev40_fu_834_p2 & cmp_i112_reg_1339_pp0_iter3_reg);

assign stream_out_TDATA = {{{r_2_fu_1126_p3}, {g_2_fu_1132_p3}}, {b_2_fu_1138_p3}};

assign stream_out_TDEST = 'bx;

assign stream_out_TID = 'bx;

assign stream_out_TKEEP = pixel_in_keep_reg_1266_pp0_iter3_reg;

assign stream_out_TLAST = pixel_in_last_reg_1276_pp0_iter3_reg;

assign stream_out_TSTRB = 'bx;

assign stream_out_TUSER = pixel_in_user_reg_1271_pp0_iter3_reg;

assign ult39_fu_560_p2 = ((row_cast_fu_543_p1 < add_i_i163) ? 1'b1 : 1'b0);

assign ult41_fu_574_p2 = ((select_ln105_1_reg_1310 < y_pos) ? 1'b1 : 1'b0);

assign ult_fu_546_p2 = ((row_cast_fu_543_p1 < add_i_i486) ? 1'b1 : 1'b0);

assign xor_ln123_fu_593_p2 = (icmp_ln123_fu_589_p2 ^ 1'd1);

assign xor_ln49_1_fu_936_p2 = (or_ln49_1_fu_905_p2 ^ 1'd1);

assign xor_ln49_2_fu_947_p2 = (or_ln49_2_fu_909_p2 ^ 1'd1);

assign xor_ln49_3_fu_965_p2 = (or_ln49_3_fu_917_p2 ^ 1'd1);

assign xor_ln49_4_fu_976_p2 = (or_ln49_4_fu_921_p2 ^ 1'd1);

assign xor_ln49_5_fu_1038_p2 = (or_ln49_5_fu_1022_p2 ^ 1'd1);

assign xor_ln49_6_fu_1056_p2 = (or_ln49_6_fu_1030_p2 ^ 1'd1);

assign xor_ln49_7_fu_1067_p2 = (or_ln49_7_fu_1034_p2 ^ 1'd1);

assign xor_ln49_fu_925_p2 = (or_ln49_fu_901_p2 ^ 1'd1);

assign zext_ln123_fu_599_p1 = select_ln105_reg_1299;

assign zext_ln125_fu_853_p1 = r_1_fu_844_p4;

assign zext_ln126_fu_866_p1 = g_1_fu_857_p4;

assign zext_ln127_fu_879_p1 = b_1_fu_870_p4;

assign zext_ln51_1_fu_651_p1 = rel_x_1_fu_641_p2;

assign zext_ln51_2_fu_667_p1 = rel_x_2_fu_657_p2;

assign zext_ln51_3_fu_683_p1 = rel_x_3_fu_678_p2;

assign zext_ln51_4_fu_698_p1 = rel_x_4_fu_693_p2;

assign zext_ln51_fu_635_p1 = rel_x_fu_625_p2;

endmodule //overlay_core_overlay_core_Pipeline_LOOP_HEIGHT_LOOP_WIDTH
