// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="overlay_core_overlay_core,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=6.667000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.275000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=636,HLS_SYN_LUT=639,HLS_VERSION=2024_1}" *)

module overlay_core (
        ap_clk,
        ap_rst_n,
        stream_in_TDATA,
        stream_in_TVALID,
        stream_in_TREADY,
        stream_in_TKEEP,
        stream_in_TSTRB,
        stream_in_TUSER,
        stream_in_TLAST,
        stream_in_TID,
        stream_in_TDEST,
        stream_out_TDATA,
        stream_out_TVALID,
        stream_out_TREADY,
        stream_out_TKEEP,
        stream_out_TSTRB,
        stream_out_TUSER,
        stream_out_TLAST,
        stream_out_TID,
        stream_out_TDEST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [23:0] stream_in_TDATA;
input   stream_in_TVALID;
output   stream_in_TREADY;
input  [2:0] stream_in_TKEEP;
input  [2:0] stream_in_TSTRB;
input  [0:0] stream_in_TUSER;
input  [0:0] stream_in_TLAST;
input  [0:0] stream_in_TID;
input  [0:0] stream_in_TDEST;
output  [23:0] stream_out_TDATA;
output   stream_out_TVALID;
input   stream_out_TREADY;
output  [2:0] stream_out_TKEEP;
output  [2:0] stream_out_TSTRB;
output  [0:0] stream_out_TUSER;
output  [0:0] stream_out_TLAST;
output  [0:0] stream_out_TID;
output  [0:0] stream_out_TDEST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;

 reg    ap_rst_n_inv;
wire   [0:0] enable;
wire   [15:0] x_pos;
wire   [15:0] y_pos;
wire   [15:0] height;
wire   [15:0] width;
reg    stream_in_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    stream_out_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] enable_read_reg_324;
wire    ap_CS_fsm_state1;
reg   [23:0] pixel_in_data_reg_328;
reg    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_state5_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
reg   [2:0] pixel_in_keep_reg_334;
reg   [2:0] pixel_in_keep_reg_334_pp0_iter1_reg;
reg   [2:0] pixel_in_strb_reg_339;
reg   [2:0] pixel_in_strb_reg_339_pp0_iter1_reg;
reg   [0:0] pixel_in_user_reg_344;
reg   [0:0] pixel_in_user_reg_344_pp0_iter1_reg;
reg   [0:0] pixel_in_last_reg_352;
reg   [0:0] pixel_in_last_reg_352_pp0_iter1_reg;
reg   [0:0] pixel_in_id_reg_360;
reg   [0:0] pixel_in_id_reg_360_pp0_iter1_reg;
reg   [0:0] pixel_in_dest_reg_365;
reg   [0:0] pixel_in_dest_reg_365_pp0_iter1_reg;
wire   [23:0] pixel_out_data_2_fu_240_p3;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [23:0] ap_phi_reg_pp0_iter0_pixel_out_data_1_reg_161;
reg   [23:0] ap_phi_reg_pp0_iter1_pixel_out_data_1_reg_161;
reg   [23:0] ap_phi_reg_pp0_iter2_pixel_out_data_1_reg_161;
reg   [15:0] empty_fu_104;
wire   [15:0] select_ln50_1_fu_291_p3;
reg   [15:0] empty_17_fu_108;
wire   [15:0] select_ln50_fu_283_p3;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln42_fu_217_p2;
wire   [0:0] icmp_ln42_1_fu_223_p2;
wire   [0:0] and_ln42_1_fu_229_p2;
wire   [0:0] or_ln42_fu_235_p2;
wire   [15:0] select_ln33_fu_259_p3;
wire   [0:0] or_ln50_fu_279_p2;
wire   [15:0] select_ln50_2_fu_272_p3;
wire   [15:0] add_ln49_fu_253_p2;
wire   [15:0] add_ln52_fu_266_p2;
reg   [1:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_stream_in_V_data_V_U_apdone_blk;
wire   [23:0] stream_in_TDATA_int_regslice;
wire    stream_in_TVALID_int_regslice;
reg    stream_in_TREADY_int_regslice;
wire    regslice_both_stream_in_V_data_V_U_ack_in;
wire    regslice_both_stream_in_V_keep_V_U_apdone_blk;
wire   [2:0] stream_in_TKEEP_int_regslice;
wire    regslice_both_stream_in_V_keep_V_U_vld_out;
wire    regslice_both_stream_in_V_keep_V_U_ack_in;
wire    regslice_both_stream_in_V_strb_V_U_apdone_blk;
wire   [2:0] stream_in_TSTRB_int_regslice;
wire    regslice_both_stream_in_V_strb_V_U_vld_out;
wire    regslice_both_stream_in_V_strb_V_U_ack_in;
wire    regslice_both_stream_in_V_user_V_U_apdone_blk;
wire   [0:0] stream_in_TUSER_int_regslice;
wire    regslice_both_stream_in_V_user_V_U_vld_out;
wire    regslice_both_stream_in_V_user_V_U_ack_in;
wire    regslice_both_stream_in_V_last_V_U_apdone_blk;
wire   [0:0] stream_in_TLAST_int_regslice;
wire    regslice_both_stream_in_V_last_V_U_vld_out;
wire    regslice_both_stream_in_V_last_V_U_ack_in;
wire    regslice_both_stream_in_V_id_V_U_apdone_blk;
wire   [0:0] stream_in_TID_int_regslice;
wire    regslice_both_stream_in_V_id_V_U_vld_out;
wire    regslice_both_stream_in_V_id_V_U_ack_in;
wire    regslice_both_stream_in_V_dest_V_U_apdone_blk;
wire   [0:0] stream_in_TDEST_int_regslice;
wire    regslice_both_stream_in_V_dest_V_U_vld_out;
wire    regslice_both_stream_in_V_dest_V_U_ack_in;
wire    regslice_both_stream_out_V_data_V_U_apdone_blk;
reg    stream_out_TVALID_int_regslice;
wire    stream_out_TREADY_int_regslice;
wire    regslice_both_stream_out_V_data_V_U_vld_out;
wire    regslice_both_stream_out_V_keep_V_U_apdone_blk;
wire    regslice_both_stream_out_V_keep_V_U_ack_in_dummy;
wire    regslice_both_stream_out_V_keep_V_U_vld_out;
wire    regslice_both_stream_out_V_strb_V_U_apdone_blk;
wire    regslice_both_stream_out_V_strb_V_U_ack_in_dummy;
wire    regslice_both_stream_out_V_strb_V_U_vld_out;
wire    regslice_both_stream_out_V_user_V_U_apdone_blk;
wire    regslice_both_stream_out_V_user_V_U_ack_in_dummy;
wire    regslice_both_stream_out_V_user_V_U_vld_out;
wire    regslice_both_stream_out_V_last_V_U_apdone_blk;
wire    regslice_both_stream_out_V_last_V_U_ack_in_dummy;
wire    regslice_both_stream_out_V_last_V_U_vld_out;
wire    regslice_both_stream_out_V_id_V_U_apdone_blk;
wire    regslice_both_stream_out_V_id_V_U_ack_in_dummy;
wire    regslice_both_stream_out_V_id_V_U_vld_out;
wire    regslice_both_stream_out_V_dest_V_U_apdone_blk;
wire    regslice_both_stream_out_V_dest_V_U_ack_in_dummy;
wire    regslice_both_stream_out_V_dest_V_U_vld_out;
reg    ap_condition_162;
reg    ap_condition_166;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 empty_fu_104 = 16'd0;
#0 empty_17_fu_108 = 16'd0;
end

overlay_core_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .enable(enable),
    .x_pos(x_pos),
    .y_pos(y_pos),
    .height(height),
    .width(width)
);

overlay_core_regslice_both #(
    .DataWidth( 24 ))
regslice_both_stream_in_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_TDATA),
    .vld_in(stream_in_TVALID),
    .ack_in(regslice_both_stream_in_V_data_V_U_ack_in),
    .data_out(stream_in_TDATA_int_regslice),
    .vld_out(stream_in_TVALID_int_regslice),
    .ack_out(stream_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_V_data_V_U_apdone_blk)
);

overlay_core_regslice_both #(
    .DataWidth( 3 ))
regslice_both_stream_in_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_TKEEP),
    .vld_in(stream_in_TVALID),
    .ack_in(regslice_both_stream_in_V_keep_V_U_ack_in),
    .data_out(stream_in_TKEEP_int_regslice),
    .vld_out(regslice_both_stream_in_V_keep_V_U_vld_out),
    .ack_out(stream_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_V_keep_V_U_apdone_blk)
);

overlay_core_regslice_both #(
    .DataWidth( 3 ))
regslice_both_stream_in_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_TSTRB),
    .vld_in(stream_in_TVALID),
    .ack_in(regslice_both_stream_in_V_strb_V_U_ack_in),
    .data_out(stream_in_TSTRB_int_regslice),
    .vld_out(regslice_both_stream_in_V_strb_V_U_vld_out),
    .ack_out(stream_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_V_strb_V_U_apdone_blk)
);

overlay_core_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_TUSER),
    .vld_in(stream_in_TVALID),
    .ack_in(regslice_both_stream_in_V_user_V_U_ack_in),
    .data_out(stream_in_TUSER_int_regslice),
    .vld_out(regslice_both_stream_in_V_user_V_U_vld_out),
    .ack_out(stream_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_V_user_V_U_apdone_blk)
);

overlay_core_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_TLAST),
    .vld_in(stream_in_TVALID),
    .ack_in(regslice_both_stream_in_V_last_V_U_ack_in),
    .data_out(stream_in_TLAST_int_regslice),
    .vld_out(regslice_both_stream_in_V_last_V_U_vld_out),
    .ack_out(stream_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_V_last_V_U_apdone_blk)
);

overlay_core_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_TID),
    .vld_in(stream_in_TVALID),
    .ack_in(regslice_both_stream_in_V_id_V_U_ack_in),
    .data_out(stream_in_TID_int_regslice),
    .vld_out(regslice_both_stream_in_V_id_V_U_vld_out),
    .ack_out(stream_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_V_id_V_U_apdone_blk)
);

overlay_core_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_TDEST),
    .vld_in(stream_in_TVALID),
    .ack_in(regslice_both_stream_in_V_dest_V_U_ack_in),
    .data_out(stream_in_TDEST_int_regslice),
    .vld_out(regslice_both_stream_in_V_dest_V_U_vld_out),
    .ack_out(stream_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_V_dest_V_U_apdone_blk)
);

overlay_core_regslice_both #(
    .DataWidth( 24 ))
regslice_both_stream_out_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(ap_phi_reg_pp0_iter2_pixel_out_data_1_reg_161),
    .vld_in(stream_out_TVALID_int_regslice),
    .ack_in(stream_out_TREADY_int_regslice),
    .data_out(stream_out_TDATA),
    .vld_out(regslice_both_stream_out_V_data_V_U_vld_out),
    .ack_out(stream_out_TREADY),
    .apdone_blk(regslice_both_stream_out_V_data_V_U_apdone_blk)
);

overlay_core_regslice_both #(
    .DataWidth( 3 ))
regslice_both_stream_out_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(pixel_in_keep_reg_334_pp0_iter1_reg),
    .vld_in(stream_out_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_V_keep_V_U_ack_in_dummy),
    .data_out(stream_out_TKEEP),
    .vld_out(regslice_both_stream_out_V_keep_V_U_vld_out),
    .ack_out(stream_out_TREADY),
    .apdone_blk(regslice_both_stream_out_V_keep_V_U_apdone_blk)
);

overlay_core_regslice_both #(
    .DataWidth( 3 ))
regslice_both_stream_out_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(pixel_in_strb_reg_339_pp0_iter1_reg),
    .vld_in(stream_out_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_V_strb_V_U_ack_in_dummy),
    .data_out(stream_out_TSTRB),
    .vld_out(regslice_both_stream_out_V_strb_V_U_vld_out),
    .ack_out(stream_out_TREADY),
    .apdone_blk(regslice_both_stream_out_V_strb_V_U_apdone_blk)
);

overlay_core_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_out_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(pixel_in_user_reg_344_pp0_iter1_reg),
    .vld_in(stream_out_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_V_user_V_U_ack_in_dummy),
    .data_out(stream_out_TUSER),
    .vld_out(regslice_both_stream_out_V_user_V_U_vld_out),
    .ack_out(stream_out_TREADY),
    .apdone_blk(regslice_both_stream_out_V_user_V_U_apdone_blk)
);

overlay_core_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_out_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(pixel_in_last_reg_352_pp0_iter1_reg),
    .vld_in(stream_out_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_V_last_V_U_ack_in_dummy),
    .data_out(stream_out_TLAST),
    .vld_out(regslice_both_stream_out_V_last_V_U_vld_out),
    .ack_out(stream_out_TREADY),
    .apdone_blk(regslice_both_stream_out_V_last_V_U_apdone_blk)
);

overlay_core_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_out_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(pixel_in_id_reg_360_pp0_iter1_reg),
    .vld_in(stream_out_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_V_id_V_U_ack_in_dummy),
    .data_out(stream_out_TID),
    .vld_out(regslice_both_stream_out_V_id_V_U_vld_out),
    .ack_out(stream_out_TREADY),
    .apdone_blk(regslice_both_stream_out_V_id_V_U_apdone_blk)
);

overlay_core_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_out_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(pixel_in_dest_reg_365_pp0_iter1_reg),
    .vld_in(stream_out_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_V_dest_V_U_ack_in_dummy),
    .data_out(stream_out_TDEST),
    .vld_out(regslice_both_stream_out_V_dest_V_U_vld_out),
    .ack_out(stream_out_TREADY),
    .apdone_blk(regslice_both_stream_out_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b1 == ap_CS_fsm_state1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((1'b1 == ap_CS_fsm_state1)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if ((1'b1 == ap_CS_fsm_state1)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_162)) begin
        if ((enable_read_reg_324 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_pixel_out_data_1_reg_161 <= stream_in_TDATA_int_regslice;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_pixel_out_data_1_reg_161 <= ap_phi_reg_pp0_iter0_pixel_out_data_1_reg_161;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_166)) begin
        if ((enable_read_reg_324 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_pixel_out_data_1_reg_161 <= pixel_out_data_2_fu_240_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_pixel_out_data_1_reg_161 <= ap_phi_reg_pp0_iter1_pixel_out_data_1_reg_161;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_17_fu_108 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        empty_17_fu_108 <= select_ln50_fu_283_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_fu_104 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        empty_fu_104 <= select_ln50_1_fu_291_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        enable_read_reg_324 <= enable;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pixel_in_data_reg_328 <= stream_in_TDATA_int_regslice;
        pixel_in_dest_reg_365 <= stream_in_TDEST_int_regslice;
        pixel_in_dest_reg_365_pp0_iter1_reg <= pixel_in_dest_reg_365;
        pixel_in_id_reg_360 <= stream_in_TID_int_regslice;
        pixel_in_id_reg_360_pp0_iter1_reg <= pixel_in_id_reg_360;
        pixel_in_keep_reg_334 <= stream_in_TKEEP_int_regslice;
        pixel_in_keep_reg_334_pp0_iter1_reg <= pixel_in_keep_reg_334;
        pixel_in_last_reg_352 <= stream_in_TLAST_int_regslice;
        pixel_in_last_reg_352_pp0_iter1_reg <= pixel_in_last_reg_352;
        pixel_in_strb_reg_339 <= stream_in_TSTRB_int_regslice;
        pixel_in_strb_reg_339_pp0_iter1_reg <= pixel_in_strb_reg_339;
        pixel_in_user_reg_344 <= stream_in_TUSER_int_regslice;
        pixel_in_user_reg_344_pp0_iter1_reg <= pixel_in_user_reg_344;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_TDATA_blk_n = stream_in_TVALID_int_regslice;
    end else begin
        stream_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_TREADY_int_regslice = 1'b1;
    end else begin
        stream_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        stream_out_TDATA_blk_n = stream_out_TREADY_int_regslice;
    end else begin
        stream_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        stream_out_TVALID_int_regslice = 1'b1;
    end else begin
        stream_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln49_fu_253_p2 = (empty_17_fu_108 + 16'd1);

assign add_ln52_fu_266_p2 = (select_ln33_fu_259_p3 + 16'd1);

assign and_ln42_1_fu_229_p2 = (icmp_ln42_fu_217_p2 & icmp_ln42_1_fu_223_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & ((stream_out_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state5_pp0_stage0_iter3))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((stream_out_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state4_pp0_stage0_iter2))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & ((stream_out_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state5_pp0_stage0_iter3))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((stream_out_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state4_pp0_stage0_iter2))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (stream_in_TVALID_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = (stream_out_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter3 = (stream_out_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_condition_162 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_166 = ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_pixel_out_data_1_reg_161 = 'bx;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign icmp_ln42_1_fu_223_p2 = ((empty_17_fu_108 < 16'd500) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_217_p2 = ((empty_fu_104 < 16'd100) ? 1'b1 : 1'b0);

assign or_ln42_fu_235_p2 = (pixel_in_user_reg_344 | and_ln42_1_fu_229_p2);

assign or_ln50_fu_279_p2 = (pixel_in_user_reg_344 | pixel_in_last_reg_352);

assign pixel_out_data_2_fu_240_p3 = ((or_ln42_fu_235_p2[0:0] == 1'b1) ? 24'd16711680 : pixel_in_data_reg_328);

assign select_ln33_fu_259_p3 = ((pixel_in_user_reg_344[0:0] == 1'b1) ? 16'd0 : empty_fu_104);

assign select_ln50_1_fu_291_p3 = ((pixel_in_last_reg_352[0:0] == 1'b1) ? add_ln52_fu_266_p2 : select_ln33_fu_259_p3);

assign select_ln50_2_fu_272_p3 = ((pixel_in_last_reg_352[0:0] == 1'b1) ? 16'd0 : 16'd1);

assign select_ln50_fu_283_p3 = ((or_ln50_fu_279_p2[0:0] == 1'b1) ? select_ln50_2_fu_272_p3 : add_ln49_fu_253_p2);

assign stream_in_TREADY = regslice_both_stream_in_V_data_V_U_ack_in;

assign stream_out_TVALID = regslice_both_stream_out_V_data_V_U_vld_out;

endmodule //overlay_core
