#ifndef EASTEREGG_H_
#define EASTEREGG_H_

#include "xil_io.h"
#include "xparameters.h"

// TODO: After integration, update this with actual address from xparameters.h
// Example: #define OVERLAY_BASEADDR XPAR_OVERLAY_CORE_0_S_AXI_CTRL_BASEADDR
#define OVERLAY_BASEADDR 0x43C00000  // Placeholder - update after integration

// Register offsets (generated by HLS for AXI-Lite interface)
#define OVERLAY_CTRL_REG    0x00  // Control register (AP_START, AP_DONE, etc.)
#define OVERLAY_GIE_REG     0x04  // Global Interrupt Enable
#define OVERLAY_IER_REG     0x08  // Interrupt Enable Register
#define OVERLAY_ISR_REG     0x0C  // Interrupt Status Register
#define OVERLAY_ENABLE_REG  0x10  // Enable bit (our custom input)
#define OVERLAY_X_POS_REG   0x18  // X position
#define OVERLAY_Y_POS_REG   0x20  // Y position
#define OVERLAY_HEIGHT_REG  0x28  // Frame height
#define OVERLAY_WIDTH_REG   0x30  // Frame width

// Control register bits
#define AP_START  0x01
#define AP_DONE   0x02
#define AP_IDLE   0x04
#define AP_READY  0x08

class EasterEggController {
public:
    EasterEggController() : active_(false) {
        // Initialize overlay as disabled
        set_enable(0);
        set_position(100, 50);  // Default position (top-left area)
        set_frame_size(1920, 1080);  // Full HD
        
        xil_printf("Easter Egg Controller initialized\r\n");
    }
    
    /**
     * Activate the easter egg overlay
     */
    void activate() {
        if (!active_) {
            set_enable(1);
            active_ = true;
            xil_printf("\r\n");
            xil_printf("******************************************\r\n");
            xil_printf("*     EASTER EGG ACTIVATED!              *\r\n");
            xil_printf("******************************************\r\n");
            xil_printf("\r\n");
        }
    }
    
    /**
     * Deactivate the easter egg overlay
     */
    void deactivate() {
        if (active_) {
            set_enable(0);
            active_ = false;
            xil_printf("Easter Egg deactivated\r\n");
        }
    }
    
    /**
     * Toggle the easter egg state
     */
    void toggle() {
        if (active_) {
            deactivate();
        } else {
            activate();
        }
    }
    
    /**
     * Check if easter egg is currently active
     */
    bool is_active() const { 
        return active_; 
    }
    
    /**
     * Set the position of the overlay
     * @param x X coordinate (0-1919 for 1080p)
     * @param y Y coordinate (0-1079 for 1080p)
     */
    void set_position(uint16_t x, uint16_t y) {
        Xil_Out32(OVERLAY_BASEADDR + OVERLAY_X_POS_REG, x);
        Xil_Out32(OVERLAY_BASEADDR + OVERLAY_Y_POS_REG, y);
        xil_printf("Overlay position set to (%d, %d)\r\n", x, y);
    }
    
    /**
     * Set the frame dimensions (should match video resolution)
     */
    void set_frame_size(uint16_t width, uint16_t height) {
        Xil_Out32(OVERLAY_BASEADDR + OVERLAY_WIDTH_REG, width);
        Xil_Out32(OVERLAY_BASEADDR + OVERLAY_HEIGHT_REG, height);
    }
    
private:
    bool active_;
    
    /**
     * Enable or disable the overlay via HLS IP
     */
    void set_enable(uint32_t enable) {
        // Write enable parameter
        Xil_Out32(OVERLAY_BASEADDR + OVERLAY_ENABLE_REG, enable);
        
        // Start the HLS IP (triggers processing)
        uint32_t ctrl = Xil_In32(OVERLAY_BASEADDR + OVERLAY_CTRL_REG);
        Xil_Out32(OVERLAY_BASEADDR + OVERLAY_CTRL_REG, ctrl | AP_START);
    }
};

#endif /* EASTEREGG_H_ */
