# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Embedded/ES4F3/Zybo-Z7-20-pcam-filter/pcam_filter.srcs/sources_1/bd/system/ip/system_video_dynclk_0/system_video_dynclk_0.xci
# IP: The module: 'system_video_dynclk_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Embedded/ES4F3/Zybo-Z7-20-pcam-filter/pcam_filter.gen/sources_1/bd/system/ip/system_video_dynclk_0/system_video_dynclk_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_video_dynclk_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Embedded/ES4F3/Zybo-Z7-20-pcam-filter/pcam_filter.gen/sources_1/bd/system/ip/system_video_dynclk_0/system_video_dynclk_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_video_dynclk_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Embedded/ES4F3/Zybo-Z7-20-pcam-filter/pcam_filter.gen/sources_1/bd/system/ip/system_video_dynclk_0/system_video_dynclk_0_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_video_dynclk_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Embedded/ES4F3/Zybo-Z7-20-pcam-filter/pcam_filter.gen/sources_1/bd/system/ip/system_video_dynclk_0/system_video_dynclk_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_video_dynclk_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Embedded/ES4F3/Zybo-Z7-20-pcam-filter/pcam_filter.srcs/sources_1/bd/system/ip/system_video_dynclk_0/system_video_dynclk_0.xci
# IP: The module: 'system_video_dynclk_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Embedded/ES4F3/Zybo-Z7-20-pcam-filter/pcam_filter.gen/sources_1/bd/system/ip/system_video_dynclk_0/system_video_dynclk_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_video_dynclk_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Embedded/ES4F3/Zybo-Z7-20-pcam-filter/pcam_filter.gen/sources_1/bd/system/ip/system_video_dynclk_0/system_video_dynclk_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_video_dynclk_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Embedded/ES4F3/Zybo-Z7-20-pcam-filter/pcam_filter.gen/sources_1/bd/system/ip/system_video_dynclk_0/system_video_dynclk_0_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_video_dynclk_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Embedded/ES4F3/Zybo-Z7-20-pcam-filter/pcam_filter.gen/sources_1/bd/system/ip/system_video_dynclk_0/system_video_dynclk_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_video_dynclk_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
