# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/ratul/ES4F3/ES4F3/project_sources/constrs_1/ZyboZ7_A.xdc

# XDC: C:/Users/ratul/ES4F3/ES4F3/project_sources/constrs_1/timing.xdc

# XDC: C:/Users/ratul/ES4F3/ES4F3/project_sources/constrs_1/auto.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_AXI_BayerToRGB_1_0/system_AXI_BayerToRGB_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_AXI_BayerToRGB_1_0 || ORIG_REF_NAME==system_AXI_BayerToRGB_1_0} -quiet] -quiet

# IP: bd/system/ip/system_AXI_GammaCorrection_0_0/system_AXI_GammaCorrection_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_AXI_GammaCorrection_0_0 || ORIG_REF_NAME==system_AXI_GammaCorrection_0_0} -quiet] -quiet

# IP: bd/system/ip/system_DVIClocking_0_0/system_DVIClocking_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_DVIClocking_0_0 || ORIG_REF_NAME==system_DVIClocking_0_0} -quiet] -quiet

# IP: bd/system/ip/system_MIPI_CSI_2_RX_0_0/system_MIPI_CSI_2_RX_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_MIPI_CSI_2_RX_0_0 || ORIG_REF_NAME==system_MIPI_CSI_2_RX_0_0} -quiet] -quiet

# IP: bd/system/ip/system_MIPI_D_PHY_RX_0_0/system_MIPI_D_PHY_RX_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_MIPI_D_PHY_RX_0_0 || ORIG_REF_NAME==system_MIPI_D_PHY_RX_0_0} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rgb2dvi_0_0/system_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rgb2dvi_0_0 || ORIG_REF_NAME==system_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_clk_wiz_0_50M_0/system_rst_clk_wiz_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_0_50M_0 || ORIG_REF_NAME==system_rst_clk_wiz_0_50M_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_vid_clk_dyn_0/system_rst_vid_clk_dyn_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_vid_clk_dyn_0 || ORIG_REF_NAME==system_rst_vid_clk_dyn_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_0/system_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_0 || ORIG_REF_NAME==system_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_1_0/system_axi_mem_intercon_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_1_0 || ORIG_REF_NAME==system_axi_mem_intercon_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/system/ip/system_video_dynclk_0/system_video_dynclk_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_video_dynclk_0 || ORIG_REF_NAME==system_video_dynclk_0} -quiet] -quiet

# IP: bd/system/ip/system_vtg_0/system_vtg_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_vtg_0 || ORIG_REF_NAME==system_vtg_0} -quiet] -quiet

# IP: bd/system/ip/system_multipix_ctrl_0_0/system_multipix_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_multipix_ctrl_0_0 || ORIG_REF_NAME==system_multipix_ctrl_0_0} -quiet] -quiet

# IP: bd/system/ip/system_singlepix_ctrl_0_0/system_singlepix_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_singlepix_ctrl_0_0 || ORIG_REF_NAME==system_singlepix_ctrl_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_2/system_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_2 || ORIG_REF_NAME==system_auto_pc_2} -quiet] -quiet

# IP: bd/system/ip/system_overlay_core_0_2/system_overlay_core_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_overlay_core_0_2 || ORIG_REF_NAME==system_overlay_core_0_2} -quiet] -quiet

# IP: bd/system/ip/system_rst_clk_wiz_0_150M_0/system_rst_clk_wiz_0_150M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_0_150M_0 || ORIG_REF_NAME==system_rst_clk_wiz_0_150M_0} -quiet] -quiet

# IP: bd/system/ip/system_smartconnect_0_0/system_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_smartconnect_0_0 || ORIG_REF_NAME==system_smartconnect_0_0} -quiet] -quiet

# XDC: c:/Users/ratul/ES4F3/ES4F3/Zybo-Z7-20-pcam-filter/pcam_filter.gen/sources_1/bd/system/system_ooc.xdc
