-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity overlay_core is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    stream_in_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    stream_in_TVALID : IN STD_LOGIC;
    stream_in_TREADY : OUT STD_LOGIC;
    stream_in_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_in_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_in_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_out_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    stream_out_TVALID : OUT STD_LOGIC;
    stream_out_TREADY : IN STD_LOGIC;
    stream_out_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    stream_out_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    stream_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_out_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_out_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of overlay_core is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "overlay_core_overlay_core,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=6.667000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.275000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1018,HLS_SYN_LUT=1105,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv24_FFFFFF : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111111111111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_FFCE : STD_LOGIC_VECTOR (15 downto 0) := "1111111111001110";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_64 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001100100";
    constant ap_const_lv16_1F4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000111110100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv16_5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000101";
    constant ap_const_lv16_FF6F : STD_LOGIC_VECTOR (15 downto 0) := "1111111101101111";
    constant ap_const_lv16_FDDF : STD_LOGIC_VECTOR (15 downto 0) := "1111110111011111";
    constant ap_const_lv16_FFBA : STD_LOGIC_VECTOR (15 downto 0) := "1111111110111010";
    constant ap_const_lv16_14 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010100";
    constant ap_const_lv16_1CC : STD_LOGIC_VECTOR (15 downto 0) := "0000000111001100";
    constant ap_const_lv16_FF92 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110010010";

    signal ap_rst_n_inv : STD_LOGIC;
    signal enable : STD_LOGIC_VECTOR (0 downto 0);
    signal x_pos : STD_LOGIC_VECTOR (15 downto 0);
    signal y_pos : STD_LOGIC_VECTOR (15 downto 0);
    signal height : STD_LOGIC_VECTOR (15 downto 0);
    signal width : STD_LOGIC_VECTOR (15 downto 0);
    signal stream_in_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal stream_out_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal empty_20_reg_183 : STD_LOGIC_VECTOR (0 downto 0);
    signal enable_read_reg_514 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal pixel_in_data_reg_519 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal pixel_in_data_reg_519_pp0_iter1_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal pixel_in_keep_reg_526 : STD_LOGIC_VECTOR (2 downto 0);
    signal pixel_in_keep_reg_526_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal pixel_in_keep_reg_526_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal pixel_in_keep_reg_526_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal pixel_in_strb_reg_531 : STD_LOGIC_VECTOR (2 downto 0);
    signal pixel_in_strb_reg_531_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal pixel_in_strb_reg_531_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal pixel_in_strb_reg_531_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal pixel_in_user_reg_536 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_user_reg_536_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_user_reg_536_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_user_reg_536_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_last_reg_545 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_last_reg_545_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_last_reg_545_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_last_reg_545_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_id_reg_553 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_id_reg_553_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_id_reg_553_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_id_reg_553_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_dest_reg_558 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_dest_reg_558_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_dest_reg_558_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_in_dest_reg_558_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln105_fu_266_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln105_reg_563 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln105_reg_563_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln105_reg_563_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln105_reg_563_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln105_1_fu_279_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln105_1_reg_568 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln116_fu_286_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln116_reg_575 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln105_2_fu_292_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln105_2_reg_581 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln116_1_fu_299_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln116_1_reg_587 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln116_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln116_reg_593 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln116_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln122_fu_385_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal and_ln126_fu_394_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln126_reg_607 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln127_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln127_reg_611 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln129_fu_439_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln129_reg_615 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln134_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln134_reg_620 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln134_reg_620_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln134_1_fu_461_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln134_1_reg_625 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln134_1_reg_625_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln139_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln139_reg_630 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln139_reg_630_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln129_fu_478_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_phi_mux_empty_20_phi_fu_187_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_pixel_out_data_2_reg_194 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter1_pixel_out_data_2_reg_194 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter2_pixel_out_data_2_reg_194 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter3_pixel_out_data_2_reg_194 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter0_pixel_out_data_1_reg_204 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter1_pixel_out_data_1_reg_204 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter2_pixel_out_data_1_reg_204 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter3_pixel_out_data_1_reg_204 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter4_pixel_out_data_1_reg_204 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_mux_pixel_out_data_4_phi_fu_220_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal pixel_out_data_3_fu_491_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter4_pixel_out_data_4_reg_216 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter0_pixel_out_data_4_reg_216 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter1_pixel_out_data_4_reg_216 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter2_pixel_out_data_4_reg_216 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter3_pixel_out_data_4_reg_216 : STD_LOGIC_VECTOR (23 downto 0);
    signal empty_fu_126 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal select_ln147_1_fu_343_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_19_fu_130 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal select_ln147_fu_335_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal select_ln105_3_fu_311_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln147_fu_331_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln147_2_fu_324_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln146_fu_305_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln149_fu_318_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln116_1_fu_365_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_fu_376_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln126_fu_389_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln127_fu_400_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln127_fu_405_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln128_fu_411_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln127_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln127_1_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln129_fu_434_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln134_fu_445_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln134_1_fu_456_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln139_fu_467_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln139_fu_482_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln139_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_stream_in_V_data_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal stream_in_TVALID_int_regslice : STD_LOGIC;
    signal stream_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_stream_in_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_TKEEP_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_stream_in_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_TSTRB_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_stream_in_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_V_user_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_stream_in_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_V_last_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_stream_in_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_V_id_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_stream_in_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_stream_in_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_V_dest_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_out_V_data_V_U_apdone_blk : STD_LOGIC;
    signal stream_out_TVALID_int_regslice : STD_LOGIC;
    signal stream_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_stream_out_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_condition_140 : BOOLEAN;
    signal ap_condition_270 : BOOLEAN;
    signal ap_condition_278 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component overlay_core_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        enable : OUT STD_LOGIC_VECTOR (0 downto 0);
        x_pos : OUT STD_LOGIC_VECTOR (15 downto 0);
        y_pos : OUT STD_LOGIC_VECTOR (15 downto 0);
        height : OUT STD_LOGIC_VECTOR (15 downto 0);
        width : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component overlay_core_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    CTRL_s_axi_U : component overlay_core_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        enable => enable,
        x_pos => x_pos,
        y_pos => y_pos,
        height => height,
        width => width);

    regslice_both_stream_in_V_data_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_TDATA,
        vld_in => stream_in_TVALID,
        ack_in => regslice_both_stream_in_V_data_V_U_ack_in,
        data_out => stream_in_TDATA_int_regslice,
        vld_out => stream_in_TVALID_int_regslice,
        ack_out => stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_V_data_V_U_apdone_blk);

    regslice_both_stream_in_V_keep_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_TKEEP,
        vld_in => stream_in_TVALID,
        ack_in => regslice_both_stream_in_V_keep_V_U_ack_in,
        data_out => stream_in_TKEEP_int_regslice,
        vld_out => regslice_both_stream_in_V_keep_V_U_vld_out,
        ack_out => stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_V_keep_V_U_apdone_blk);

    regslice_both_stream_in_V_strb_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_TSTRB,
        vld_in => stream_in_TVALID,
        ack_in => regslice_both_stream_in_V_strb_V_U_ack_in,
        data_out => stream_in_TSTRB_int_regslice,
        vld_out => regslice_both_stream_in_V_strb_V_U_vld_out,
        ack_out => stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_V_strb_V_U_apdone_blk);

    regslice_both_stream_in_V_user_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_TUSER,
        vld_in => stream_in_TVALID,
        ack_in => regslice_both_stream_in_V_user_V_U_ack_in,
        data_out => stream_in_TUSER_int_regslice,
        vld_out => regslice_both_stream_in_V_user_V_U_vld_out,
        ack_out => stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_V_user_V_U_apdone_blk);

    regslice_both_stream_in_V_last_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_TLAST,
        vld_in => stream_in_TVALID,
        ack_in => regslice_both_stream_in_V_last_V_U_ack_in,
        data_out => stream_in_TLAST_int_regslice,
        vld_out => regslice_both_stream_in_V_last_V_U_vld_out,
        ack_out => stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_V_last_V_U_apdone_blk);

    regslice_both_stream_in_V_id_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_TID,
        vld_in => stream_in_TVALID,
        ack_in => regslice_both_stream_in_V_id_V_U_ack_in,
        data_out => stream_in_TID_int_regslice,
        vld_out => regslice_both_stream_in_V_id_V_U_vld_out,
        ack_out => stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_V_id_V_U_apdone_blk);

    regslice_both_stream_in_V_dest_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_TDEST,
        vld_in => stream_in_TVALID,
        ack_in => regslice_both_stream_in_V_dest_V_U_ack_in,
        data_out => stream_in_TDEST_int_regslice,
        vld_out => regslice_both_stream_in_V_dest_V_U_vld_out,
        ack_out => stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_V_dest_V_U_apdone_blk);

    regslice_both_stream_out_V_data_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_phi_mux_pixel_out_data_4_phi_fu_220_p4,
        vld_in => stream_out_TVALID_int_regslice,
        ack_in => stream_out_TREADY_int_regslice,
        data_out => stream_out_TDATA,
        vld_out => regslice_both_stream_out_V_data_V_U_vld_out,
        ack_out => stream_out_TREADY,
        apdone_blk => regslice_both_stream_out_V_data_V_U_apdone_blk);

    regslice_both_stream_out_V_keep_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => pixel_in_keep_reg_526_pp0_iter3_reg,
        vld_in => stream_out_TVALID_int_regslice,
        ack_in => regslice_both_stream_out_V_keep_V_U_ack_in_dummy,
        data_out => stream_out_TKEEP,
        vld_out => regslice_both_stream_out_V_keep_V_U_vld_out,
        ack_out => stream_out_TREADY,
        apdone_blk => regslice_both_stream_out_V_keep_V_U_apdone_blk);

    regslice_both_stream_out_V_strb_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => pixel_in_strb_reg_531_pp0_iter3_reg,
        vld_in => stream_out_TVALID_int_regslice,
        ack_in => regslice_both_stream_out_V_strb_V_U_ack_in_dummy,
        data_out => stream_out_TSTRB,
        vld_out => regslice_both_stream_out_V_strb_V_U_vld_out,
        ack_out => stream_out_TREADY,
        apdone_blk => regslice_both_stream_out_V_strb_V_U_apdone_blk);

    regslice_both_stream_out_V_user_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => pixel_in_user_reg_536_pp0_iter3_reg,
        vld_in => stream_out_TVALID_int_regslice,
        ack_in => regslice_both_stream_out_V_user_V_U_ack_in_dummy,
        data_out => stream_out_TUSER,
        vld_out => regslice_both_stream_out_V_user_V_U_vld_out,
        ack_out => stream_out_TREADY,
        apdone_blk => regslice_both_stream_out_V_user_V_U_apdone_blk);

    regslice_both_stream_out_V_last_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => pixel_in_last_reg_545_pp0_iter3_reg,
        vld_in => stream_out_TVALID_int_regslice,
        ack_in => regslice_both_stream_out_V_last_V_U_ack_in_dummy,
        data_out => stream_out_TLAST,
        vld_out => regslice_both_stream_out_V_last_V_U_vld_out,
        ack_out => stream_out_TREADY,
        apdone_blk => regslice_both_stream_out_V_last_V_U_apdone_blk);

    regslice_both_stream_out_V_id_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => pixel_in_id_reg_553_pp0_iter3_reg,
        vld_in => stream_out_TVALID_int_regslice,
        ack_in => regslice_both_stream_out_V_id_V_U_ack_in_dummy,
        data_out => stream_out_TID,
        vld_out => regslice_both_stream_out_V_id_V_U_vld_out,
        ack_out => stream_out_TREADY,
        apdone_blk => regslice_both_stream_out_V_id_V_U_apdone_blk);

    regslice_both_stream_out_V_dest_V_U : component overlay_core_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => pixel_in_dest_reg_558_pp0_iter3_reg,
        vld_in => stream_out_TVALID_int_regslice,
        ack_in => regslice_both_stream_out_V_dest_V_U_ack_in_dummy,
        data_out => stream_out_TDEST,
        vld_out => regslice_both_stream_out_V_dest_V_U_vld_out,
        ack_out => stream_out_TREADY,
        apdone_blk => regslice_both_stream_out_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_pixel_out_data_4_reg_216_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_140)) then
                if ((select_ln105_fu_266_p3 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter1_pixel_out_data_4_reg_216 <= stream_in_TDATA_int_regslice;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_pixel_out_data_4_reg_216 <= ap_phi_reg_pp0_iter0_pixel_out_data_4_reg_216;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_pixel_out_data_2_reg_194_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                if (((ap_const_lv1_0 = and_ln116_fu_370_p2) and (select_ln105_reg_563_pp0_iter1_reg = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter3_pixel_out_data_2_reg_194 <= pixel_in_data_reg_519_pp0_iter1_reg;
                elsif (((ap_const_lv1_1 = and_ln116_fu_370_p2) and (select_ln105_reg_563_pp0_iter1_reg = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter3_pixel_out_data_2_reg_194 <= zext_ln122_fu_385_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_pixel_out_data_2_reg_194 <= ap_phi_reg_pp0_iter2_pixel_out_data_2_reg_194;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter4_pixel_out_data_1_reg_204_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_278)) then 
                    ap_phi_reg_pp0_iter4_pixel_out_data_1_reg_204 <= ap_phi_reg_pp0_iter3_pixel_out_data_2_reg_194;
                elsif ((ap_const_boolean_1 = ap_condition_270)) then 
                    ap_phi_reg_pp0_iter4_pixel_out_data_1_reg_204 <= ap_const_lv24_FFFFFF;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_pixel_out_data_1_reg_204 <= ap_phi_reg_pp0_iter3_pixel_out_data_1_reg_204;
                end if;
            end if; 
        end if;
    end process;

    empty_19_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                empty_19_fu_130 <= ap_const_lv16_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                empty_19_fu_130 <= select_ln147_fu_335_p3;
            end if; 
        end if;
    end process;

    empty_20_reg_183_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                empty_20_reg_183 <= select_ln105_reg_563;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                empty_20_reg_183 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    empty_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                empty_fu_126 <= ap_const_lv16_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                empty_fu_126 <= select_ln147_1_fu_343_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln116_1_reg_587 <= add_ln116_1_fu_299_p2;
                add_ln116_reg_575 <= add_ln116_fu_286_p2;
                pixel_in_data_reg_519 <= stream_in_TDATA_int_regslice;
                pixel_in_data_reg_519_pp0_iter1_reg <= pixel_in_data_reg_519;
                pixel_in_dest_reg_558 <= stream_in_TDEST_int_regslice;
                pixel_in_dest_reg_558_pp0_iter1_reg <= pixel_in_dest_reg_558;
                pixel_in_id_reg_553 <= stream_in_TID_int_regslice;
                pixel_in_id_reg_553_pp0_iter1_reg <= pixel_in_id_reg_553;
                pixel_in_keep_reg_526 <= stream_in_TKEEP_int_regslice;
                pixel_in_keep_reg_526_pp0_iter1_reg <= pixel_in_keep_reg_526;
                pixel_in_last_reg_545 <= stream_in_TLAST_int_regslice;
                pixel_in_last_reg_545_pp0_iter1_reg <= pixel_in_last_reg_545;
                pixel_in_strb_reg_531 <= stream_in_TSTRB_int_regslice;
                pixel_in_strb_reg_531_pp0_iter1_reg <= pixel_in_strb_reg_531;
                pixel_in_user_reg_536 <= stream_in_TUSER_int_regslice;
                pixel_in_user_reg_536_pp0_iter1_reg <= pixel_in_user_reg_536;
                select_ln105_1_reg_568 <= select_ln105_1_fu_279_p3;
                select_ln105_2_reg_581 <= select_ln105_2_fu_292_p3;
                select_ln105_reg_563_pp0_iter1_reg <= select_ln105_reg_563;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                and_ln126_reg_607 <= and_ln126_fu_394_p2;
                icmp_ln116_reg_593 <= icmp_ln116_fu_360_p2;
                icmp_ln129_reg_615 <= icmp_ln129_fu_439_p2;
                icmp_ln134_1_reg_625 <= icmp_ln134_1_fu_461_p2;
                icmp_ln134_1_reg_625_pp0_iter3_reg <= icmp_ln134_1_reg_625;
                icmp_ln134_reg_620 <= icmp_ln134_fu_450_p2;
                icmp_ln134_reg_620_pp0_iter3_reg <= icmp_ln134_reg_620;
                icmp_ln139_reg_630 <= icmp_ln139_fu_472_p2;
                icmp_ln139_reg_630_pp0_iter3_reg <= icmp_ln139_reg_630;
                or_ln127_reg_611 <= or_ln127_fu_428_p2;
                pixel_in_dest_reg_558_pp0_iter2_reg <= pixel_in_dest_reg_558_pp0_iter1_reg;
                pixel_in_dest_reg_558_pp0_iter3_reg <= pixel_in_dest_reg_558_pp0_iter2_reg;
                pixel_in_id_reg_553_pp0_iter2_reg <= pixel_in_id_reg_553_pp0_iter1_reg;
                pixel_in_id_reg_553_pp0_iter3_reg <= pixel_in_id_reg_553_pp0_iter2_reg;
                pixel_in_keep_reg_526_pp0_iter2_reg <= pixel_in_keep_reg_526_pp0_iter1_reg;
                pixel_in_keep_reg_526_pp0_iter3_reg <= pixel_in_keep_reg_526_pp0_iter2_reg;
                pixel_in_last_reg_545_pp0_iter2_reg <= pixel_in_last_reg_545_pp0_iter1_reg;
                pixel_in_last_reg_545_pp0_iter3_reg <= pixel_in_last_reg_545_pp0_iter2_reg;
                pixel_in_strb_reg_531_pp0_iter2_reg <= pixel_in_strb_reg_531_pp0_iter1_reg;
                pixel_in_strb_reg_531_pp0_iter3_reg <= pixel_in_strb_reg_531_pp0_iter2_reg;
                pixel_in_user_reg_536_pp0_iter2_reg <= pixel_in_user_reg_536_pp0_iter1_reg;
                pixel_in_user_reg_536_pp0_iter3_reg <= pixel_in_user_reg_536_pp0_iter2_reg;
                select_ln105_reg_563_pp0_iter2_reg <= select_ln105_reg_563_pp0_iter1_reg;
                select_ln105_reg_563_pp0_iter3_reg <= select_ln105_reg_563_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_pixel_out_data_1_reg_204 <= ap_phi_reg_pp0_iter0_pixel_out_data_1_reg_204;
                ap_phi_reg_pp0_iter1_pixel_out_data_2_reg_194 <= ap_phi_reg_pp0_iter0_pixel_out_data_2_reg_194;
                select_ln105_reg_563 <= select_ln105_fu_266_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter2_pixel_out_data_1_reg_204 <= ap_phi_reg_pp0_iter1_pixel_out_data_1_reg_204;
                ap_phi_reg_pp0_iter2_pixel_out_data_2_reg_194 <= ap_phi_reg_pp0_iter1_pixel_out_data_2_reg_194;
                ap_phi_reg_pp0_iter2_pixel_out_data_4_reg_216 <= ap_phi_reg_pp0_iter1_pixel_out_data_4_reg_216;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter3_pixel_out_data_1_reg_204 <= ap_phi_reg_pp0_iter2_pixel_out_data_1_reg_204;
                ap_phi_reg_pp0_iter3_pixel_out_data_4_reg_216 <= ap_phi_reg_pp0_iter2_pixel_out_data_4_reg_216;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter4_pixel_out_data_4_reg_216 <= ap_phi_reg_pp0_iter3_pixel_out_data_4_reg_216;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                enable_read_reg_514 <= enable;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln116_1_fu_299_p2 <= std_logic_vector(unsigned(select_ln105_2_fu_292_p3) + unsigned(ap_const_lv16_FFCE));
    add_ln116_fu_286_p2 <= std_logic_vector(unsigned(select_ln105_1_fu_279_p3) + unsigned(ap_const_lv16_FFCE));
    add_ln127_fu_400_p2 <= std_logic_vector(unsigned(select_ln105_1_reg_568) + unsigned(ap_const_lv16_FF6F));
    add_ln129_fu_434_p2 <= std_logic_vector(unsigned(select_ln105_2_reg_581) + unsigned(ap_const_lv16_FDDF));
    add_ln134_1_fu_456_p2 <= std_logic_vector(unsigned(select_ln105_2_reg_581) + unsigned(ap_const_lv16_FFBA));
    add_ln134_fu_445_p2 <= std_logic_vector(unsigned(select_ln105_1_reg_568) + unsigned(ap_const_lv16_FFBA));
    add_ln139_fu_467_p2 <= std_logic_vector(unsigned(select_ln105_1_reg_568) + unsigned(ap_const_lv16_FF92));
    add_ln146_fu_305_p2 <= std_logic_vector(unsigned(empty_19_fu_130) + unsigned(ap_const_lv16_1));
    add_ln149_fu_318_p2 <= std_logic_vector(unsigned(select_ln105_3_fu_311_p3) + unsigned(ap_const_lv16_1));
    and_ln116_fu_370_p2 <= (icmp_ln116_fu_360_p2 and icmp_ln116_1_fu_365_p2);
    and_ln126_fu_394_p2 <= (icmp_ln126_fu_389_p2 and icmp_ln116_1_fu_365_p2);
    and_ln127_1_fu_422_p2 <= (icmp_ln128_fu_411_p2 and icmp_ln116_fu_360_p2);
    and_ln127_fu_416_p2 <= (icmp_ln127_fu_405_p2 and icmp_ln116_1_fu_365_p2);
    and_ln129_fu_478_p2 <= (icmp_ln129_reg_615 and icmp_ln116_reg_593);
    and_ln139_fu_486_p2 <= (or_ln139_fu_482_p2 and icmp_ln134_1_reg_625_pp0_iter3_reg);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_block_state2_pp0_stage0_iter0, ap_block_state6_pp0_stage0_iter4, ap_block_state7_pp0_stage0_iter5)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter5)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter4)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_block_state2_pp0_stage0_iter0, ap_block_state6_pp0_stage0_iter4, ap_block_state7_pp0_stage0_iter5, stream_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((stream_out_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter5))) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and ((stream_out_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter4))) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_block_state2_pp0_stage0_iter0, ap_block_state6_pp0_stage0_iter4, ap_block_state7_pp0_stage0_iter5, stream_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((stream_out_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter5))) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and ((stream_out_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter4))) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter0)));
    end process;


    ap_block_state2_pp0_stage0_iter0_assign_proc : process(stream_in_TVALID_int_regslice)
    begin
                ap_block_state2_pp0_stage0_iter0 <= (stream_in_TVALID_int_regslice = ap_const_logic_0);
    end process;


    ap_block_state6_pp0_stage0_iter4_assign_proc : process(stream_out_TREADY_int_regslice)
    begin
                ap_block_state6_pp0_stage0_iter4 <= (stream_out_TREADY_int_regslice = ap_const_logic_0);
    end process;


    ap_block_state7_pp0_stage0_iter5_assign_proc : process(stream_out_TREADY_int_regslice)
    begin
                ap_block_state7_pp0_stage0_iter5 <= (stream_out_TREADY_int_regslice = ap_const_logic_0);
    end process;


    ap_condition_140_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_140 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_270_assign_proc : process(select_ln105_reg_563_pp0_iter2_reg, and_ln126_reg_607, or_ln127_reg_611, and_ln129_fu_478_p2)
    begin
                ap_condition_270 <= ((((or_ln127_reg_611 = ap_const_lv1_1) and (select_ln105_reg_563_pp0_iter2_reg = ap_const_lv1_1)) or ((ap_const_lv1_1 = and_ln129_fu_478_p2) and (select_ln105_reg_563_pp0_iter2_reg = ap_const_lv1_1))) or ((ap_const_lv1_1 = and_ln126_reg_607) and (select_ln105_reg_563_pp0_iter2_reg = ap_const_lv1_1)));
    end process;


    ap_condition_278_assign_proc : process(select_ln105_reg_563_pp0_iter2_reg, and_ln126_reg_607, or_ln127_reg_611, and_ln129_fu_478_p2)
    begin
                ap_condition_278 <= ((ap_const_lv1_0 = and_ln129_fu_478_p2) and (ap_const_lv1_0 = and_ln126_reg_607) and (or_ln127_reg_611 = ap_const_lv1_0) and (select_ln105_reg_563_pp0_iter2_reg = ap_const_lv1_1));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_empty_20_phi_fu_187_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, empty_20_reg_183, select_ln105_reg_563, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_empty_20_phi_fu_187_p4 <= select_ln105_reg_563;
        else 
            ap_phi_mux_empty_20_phi_fu_187_p4 <= empty_20_reg_183;
        end if; 
    end process;


    ap_phi_mux_pixel_out_data_4_phi_fu_220_p4_assign_proc : process(select_ln105_reg_563_pp0_iter3_reg, pixel_out_data_3_fu_491_p3, ap_phi_reg_pp0_iter4_pixel_out_data_4_reg_216)
    begin
        if ((select_ln105_reg_563_pp0_iter3_reg = ap_const_lv1_1)) then 
            ap_phi_mux_pixel_out_data_4_phi_fu_220_p4 <= pixel_out_data_3_fu_491_p3;
        else 
            ap_phi_mux_pixel_out_data_4_phi_fu_220_p4 <= ap_phi_reg_pp0_iter4_pixel_out_data_4_reg_216;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_pixel_out_data_1_reg_204 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_pixel_out_data_2_reg_194 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_pixel_out_data_4_reg_216 <= "XXXXXXXXXXXXXXXXXXXXXXXX";

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    b_fu_376_p4 <= pixel_in_data_reg_519_pp0_iter1_reg(7 downto 1);
    icmp_ln116_1_fu_365_p2 <= "1" when (unsigned(add_ln116_1_reg_587) < unsigned(ap_const_lv16_1F4)) else "0";
    icmp_ln116_fu_360_p2 <= "1" when (unsigned(add_ln116_reg_575) < unsigned(ap_const_lv16_64)) else "0";
    icmp_ln126_fu_389_p2 <= "1" when (unsigned(add_ln116_reg_575) < unsigned(ap_const_lv16_5)) else "0";
    icmp_ln127_fu_405_p2 <= "1" when (unsigned(add_ln127_fu_400_p2) < unsigned(ap_const_lv16_5)) else "0";
    icmp_ln128_fu_411_p2 <= "1" when (unsigned(add_ln116_1_reg_587) < unsigned(ap_const_lv16_5)) else "0";
    icmp_ln129_fu_439_p2 <= "1" when (unsigned(add_ln129_fu_434_p2) < unsigned(ap_const_lv16_5)) else "0";
    icmp_ln134_1_fu_461_p2 <= "1" when (unsigned(add_ln134_1_fu_456_p2) < unsigned(ap_const_lv16_1CC)) else "0";
    icmp_ln134_fu_450_p2 <= "1" when (unsigned(add_ln134_fu_445_p2) < unsigned(ap_const_lv16_14)) else "0";
    icmp_ln139_fu_472_p2 <= "1" when (unsigned(add_ln139_fu_467_p2) < unsigned(ap_const_lv16_14)) else "0";
    or_ln127_fu_428_p2 <= (and_ln127_fu_416_p2 or and_ln127_1_fu_422_p2);
    or_ln139_fu_482_p2 <= (icmp_ln139_reg_630_pp0_iter3_reg or icmp_ln134_reg_620_pp0_iter3_reg);
    or_ln147_fu_331_p2 <= (pixel_in_user_reg_536 or pixel_in_last_reg_545);
    pixel_out_data_3_fu_491_p3 <= 
        ap_const_lv24_FFFFFF when (and_ln139_fu_486_p2(0) = '1') else 
        ap_phi_reg_pp0_iter4_pixel_out_data_1_reg_204;
    select_ln105_1_fu_279_p3 <= 
        ap_const_lv16_0 when (pixel_in_user_reg_536(0) = '1') else 
        empty_fu_126;
    select_ln105_2_fu_292_p3 <= 
        ap_const_lv16_0 when (pixel_in_user_reg_536(0) = '1') else 
        empty_19_fu_130;
    select_ln105_3_fu_311_p3 <= 
        ap_const_lv16_0 when (pixel_in_user_reg_536(0) = '1') else 
        empty_fu_126;
    select_ln105_fu_266_p3 <= 
        enable_read_reg_514 when (stream_in_TUSER_int_regslice(0) = '1') else 
        ap_phi_mux_empty_20_phi_fu_187_p4;
    select_ln147_1_fu_343_p3 <= 
        add_ln149_fu_318_p2 when (pixel_in_last_reg_545(0) = '1') else 
        select_ln105_3_fu_311_p3;
    select_ln147_2_fu_324_p3 <= 
        ap_const_lv16_0 when (pixel_in_last_reg_545(0) = '1') else 
        ap_const_lv16_1;
    select_ln147_fu_335_p3 <= 
        select_ln147_2_fu_324_p3 when (or_ln147_fu_331_p2(0) = '1') else 
        add_ln146_fu_305_p2;

    stream_in_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, stream_in_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_TDATA_blk_n <= stream_in_TVALID_int_regslice;
        else 
            stream_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_in_TREADY <= regslice_both_stream_in_V_data_V_U_ack_in;

    stream_in_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_TREADY_int_regslice <= ap_const_logic_1;
        else 
            stream_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    stream_out_TDATA_blk_n_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, stream_out_TREADY_int_regslice)
    begin
        if ((((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            stream_out_TDATA_blk_n <= stream_out_TREADY_int_regslice;
        else 
            stream_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_out_TVALID <= regslice_both_stream_out_V_data_V_U_vld_out;

    stream_out_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            stream_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            stream_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln122_fu_385_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_fu_376_p4),24));
end behav;
